### ISSUE TITLE
'[ERROR] FloatDomainError, Infinity' when >Rpush push

### ISSUE THREAD

**Issue by casertap** [rpush/rpush#118]
I followed the exact procedure to migrate from rapns to rpush.
Everything seems ok so I decided to run the example in the rails console.
```
n = Rpush::Apns::Notification.new
n.app = Rpush::Apns::App.find_by_name("ios_app")
n.device_token = "..." # 64-character hex string
n.alert = "hi mom!"
n.save!
Rpush.push
```

and I get this stack when executing rpush/daemon/apprunner.rb:18 
```
@runners[app_id].enqueue(group) if @runners[app_id]
```

more precisely app_runner.rb:122
```
batch_size = (notifications.size / num_dispatcher_loops.to_f).ceil
```

I have copy pasted the configuration file from: https://github.com/rpush/rpush/wiki/Configuration
```
MacBook-Pro-de-Pierre-2:rails-app pierre$ rails c
Loading development environment (Rails 4.0.12)
2.0.0-p598 :001 > Rpush.push
  Rpush::Client::ActiveRecord::App Load (0.3ms)  SELECT `rpush_apps`.* FROM `rpush_apps`
   (0.1ms)  BEGIN
  Rpush::Client::ActiveRecord::Notification Load (0.4ms)  SELECT `rpush_notifications`.* FROM `rpush_notifications` WHERE (processing = 0 AND delivered = 0 AND failed = 0 AND (deliver_after IS NULL OR deliver_after < '2015-01-19 11:12:07')) ORDER BY created_at ASC LIMIT 100 FOR UPDATE
  SQL (0.3ms)  UPDATE `rpush_notifications` SET processing = 1 WHERE `rpush_notifications`.`id` IN (33031)
   (21.1ms)  COMMIT
[2015-01-19 12:12:07] [ERROR] FloatDomainError, Infinity
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/daemon/app_runner.rb:117:in `ceil'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/daemon/app_runner.rb:117:in `enqueue'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/daemon/app_runner.rb:20:in `block in enqueue'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/daemon/app_runner.rb:18:in `each'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/daemon/app_runner.rb:18:in `enqueue'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/daemon/feeder.rb:43:in `enqueue_notifications'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/daemon/feeder.rb:8:in `start'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/rpush-2.2.0/lib/rpush/push.rb:12:in `push'
(irb):1:in `irb_binding'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/workspace.rb:86:in `eval'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/workspace.rb:86:in `evaluate'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/context.rb:380:in `evaluate'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:492:in `block (2 levels) in eval_input'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:624:in `signal_status'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:489:in `block in eval_input'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in `loop'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in `catch'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:488:in `eval_input'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:397:in `block in start'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:396:in `catch'
/Users/pierrecaserta/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:396:in `start'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.0.12/lib/rails/commands/console.rb:90:in `start'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.0.12/lib/rails/commands/console.rb:9:in `start'
/Users/pierrecaserta/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.0.12/lib/rails/commands.rb:62:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
 => {} 
2.0.0-p598 :002 > 
```

**Comment by casertap** [comment]
I added some log in app_runner.rb:
```
def self.enqueue(notifications)
        ap notifications
        notifications.group_by(&:app_id).each do |app_id, group|
          start_app_with_id(app_id) unless @runners[app_id]
          ap @runners[app_id]
          ap group
          @runners[app_id].enqueue(group) if @runners[app_id]
        end

        ProcTitle.update
      end
```
```
2.0.0-p598 :006 > Rpush.push
[
    [0] #<Rpush::Client::ActiveRecord::Apns::Notification:0x007fb60ee61a60> {
                       :id => 33038,
                    :badge => nil,
             :device_token => "d1e4c1...b150",
                    :sound => "default",
                    :alert => "hi mom! TESTTEST8",
                     :data => nil,
                   :expiry => 86400,
                :delivered => false,
             :delivered_at => nil,
                   :failed => false,
                :failed_at => nil,
               :error_code => nil,
        :error_description => nil,
            :deliver_after => nil,
               :created_at => Mon, 19 Jan 2015 15:52:33 CET +01:00,
               :updated_at => Mon, 19 Jan 2015 15:52:33 CET +01:00,
            :alert_is_json => false,
                     :type => "Rpush::Client::ActiveRecord::Apns::Notification",
             :collapse_key => nil,
         :delay_while_idle => false,
         :registration_ids => nil,
                   :app_id => 1,
                  :retries => 0,
                      :uri => nil,
               :fail_after => nil,
               :processing => true,
                 :priority => nil,
                 :url_args => nil,
                 :category => nil
    }
]
#<Rpush::Daemon::AppRunner:0x007fb60edf3d58 @app=#<Rpush::Client::ActiveRecord::Apns::App id: 1, name: "ios_app", environment: "production", certificate: "Bag Attributes\n    friendlyName: Apple Development ...", password: "", connections: 0, created_at: "2013-12-24 10:07:38", updated_at: "2013-12-24 10:07:38", type: "Rpush::Client::ActiveRecord::Apns::App", auth_key: nil, client_id: nil, client_secret: nil, access_token: nil, access_token_expiration: nil>, @loops=[], @dispatcher_loops=[], @service=Rpush::Daemon::Apns, @queue=#<Queue:0x007fb60ee10f70 @que=[], @num_waiting=0, @mutex=#<Mutex:0x007fb60ee10e08>, @cond=#<ConditionVariable:0x007fb60ee10d68 @waiters={}, @waiters_mutex=#<Mutex:0x007fb60ee10c78>>>>
[
    [0] #<Rpush::Client::ActiveRecord::Apns::Notification:0x007fb60ee61a60> {
                       :id => 33038,
                    :badge => nil,
             :device_token => "d1e4c1c...b150",
                    :sound => "default",
                    :alert => "hi mom! TESTTEST8",
                     :data => nil,
                   :expiry => 86400,
                :delivered => false,
             :delivered_at => nil,
                   :failed => false,
                :failed_at => nil,
               :error_code => nil,
        :error_description => nil,
            :deliver_after => nil,
               :created_at => Mon, 19 Jan 2015 15:52:33 CET +01:00,
               :updated_at => Mon, 19 Jan 2015 15:52:33 CET +01:00,
            :alert_is_json => false,
                     :type => "Rpush::Client::ActiveRecord::Apns::Notification",
             :collapse_key => nil,
         :delay_while_idle => false,
         :registration_ids => nil,
                   :app_id => 1,
                  :retries => 0,
                      :uri => nil,
               :fail_after => nil,
               :processing => true,
                 :priority => nil,
                 :url_args => nil,
                 :category => nil
    }
]
[2015-01-19 15:52:36] [ERROR] FloatDomainError, Infinity
```

**Comment by ileitch** [comment]
What does `Rpush::Apns::App.find(1).connections` give you?

**Comment by casertap** [comment]
It gives me 0... I see.
So I changed it for 1 and now it is working a little bit better Thanks.
Now I see that on notification_delivered is called even if I do not receive the push on my phone yet.

I still have some questions, please.
My certificate says " Apple Development IOS Push Services" does this mean that I need to have the environment column set to "development" ?
When I run: "bundle exec rpush start" it says  "Booting Rails 'development' environment..." How do I start it in production please?

**Comment by casertap** [comment]
if I create a new notification and than run the command
```
Rpush.push
```
 the method on notification_delivered is runned so that's better (but I do not see the push on my phone yet). 
If I open another console and run
```
bundle exec rpush start
```
it says "Booting Rails 'development' environment..." and when I create a new notification and save! 
it says "invalid token"

**Comment by ileitch** [comment]
`Booting Rails 'development' environment...` here `development` is your Rails environment. The APNs environment is defined on the App instance with the `environment` attribute. You can set it to either `sandbox` or `production`.

**Comment by ileitch** [comment]
What does your device token look like? It needs to be 64 character base64 encoded string.

**Comment by casertap** [comment]
Ok I understand, I need to run 
```
bundle exec rpush start -e production
```
to start it in production mode and I need to have the right environment attribute set in my DB, thanks.

The device_token is different for each user and look like this:
"<44fa009e 963f15df 1ed9a99f 438fdd0b 3cff516b 5bfc2dfd 19c712ea 25c3c7ac>"
Do I need to remove the < > ? it worked with Rapns.

**Comment by casertap** [comment]
I thought I could log to a friend account and use his device token to test the push feature on my phone but it is not the case with my application because the iphone app does not regenerate token every time someone is logged in (I need to change that).
So I was using someone else account on my phone to test the push feature but I kept his device_token.

I logged with my account and I generate my own device token and I get the same result using both method (Rpush.push and rpush start). I do not see the push notification yet but it is getting closer.

**Comment by ileitch** [comment]
Any luck?

**Comment by casertap** [comment]
I could manage to have notification on my iphone on localhost. :-) I also didn't know that I needed to have the application in the background to really be notified. 
I will try in production next week. Thanks ileitch for your plugin, it is awesome. Keep up the good work.

**Comment by ileitch** [comment]
Good to hear, please open a new issue if you run into any more problems.
