### ISSUE TITLE
Rpush 2.4.0 throwing silent ActiveRecord::SubclassNotFound error.

### ISSUE THREAD

**Issue by skunkworker** [rpush/rpush#145]
Hi I am running rpush 2.4.0 on Rails 3.2.21 with Ruby 2.1.2. After starting rpush using the rpush start command the server quits immediately and no error is thrown in the log file. But when I call > Rpush.push in the rails console it throws an error.

```
2.1.2 :001 > Rpush.push
ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: 'Rpush::Gcm::App'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Rpush::Client::ActiveRecord::App.inheritance_column to use another column for that information.
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/inheritance.rb:143:in `rescue in find_sti_class'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/inheritance.rb:136:in `find_sti_class'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/inheritance.rb:62:in `instantiate'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/querying.rb:38:in `block (2 levels) in find_by_sql'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/querying.rb:38:in `collect!'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/querying.rb:38:in `block in find_by_sql'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/explain.rb:41:in `logging_query_plan'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/querying.rb:37:in `find_by_sql'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/relation.rb:171:in `exec_queries'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/relation.rb:160:in `block in to_a'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/explain.rb:34:in `logging_query_plan'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/relation.rb:159:in `to_a'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/relation/finder_methods.rb:159:in `all'
from /usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/querying.rb:5:in `all'
from /usr/local/rvm/gems/ruby-2.1.2/gems/rpush-2.4.0/lib/rpush/daemon/store/active_record.rb:26:in `all_apps'
from /usr/local/rvm/gems/ruby-2.1.2/gems/rpush-2.4.0/lib/rpush/daemon/synchronizer.rb:8:in `sync'
from /usr/local/rvm/gems/ruby-2.1.2/gems/rpush-2.4.0/lib/rpush/push.rb:16:in `push'
from (irb):1
from /usr/local/rvm/gems/ruby-2.1.2/gems/railties-3.2.21/lib/rails/commands/console.rb:47:in `start'
from /usr/local/rvm/gems/ruby-2.1.2/gems/railties-3.2.21/lib/rails/commands/console.rb:8:in `start'
from /usr/local/rvm/gems/ruby-2.1.2/gems/railties-3.2.21/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'2.1.2 :002 > Rpush::Apns::App
=> Rpush::Client::ActiveRecord::Apns::App(id: integer, name: string, environment: string, certificate: text, password: string, connections: integer, created_at: datetime, updated_at: datetime, type: string, auth_key: string, client_id: string, client_secret: string, access_token: string, access_token_expiration: datetime) 
```

When I reverted to Rpush 2.3.2 the error in the console went away and the server started up normally.

**Comment by CR4567** [comment]
Same error is there a solution already available?

**Comment by mborsten** [comment]
Same error here

**Comment by RaghavVishnoi** [comment]
use command: rpush init 
it'll generate migrations it self then 
rake db:migrate

**Comment by aried3r** [comment]
I could not reproduce this. Feel free to open a new issue if this is still a problem.
