### ISSUE TITLE
NoMethodError, undefined method `service_name'

### ISSUE THREAD

**Issue by avolkovi** [rpush/rpush#158]
We're using the Rpush 2.4.0 with `:active_record` client on Rails 4.0.13

Simple config, only one sandbox app, trying to send a single notification by running `Rpush.push` in a rails console

```
[2015-05-28 15:30:44] [ERROR] NoMethodError, undefined method `service_name' for #<Rpush::Client::ActiveRecord::App:0x007f1e7d62c8f0>
/data/iknow/shared/bundle/ruby/2.1.0/gems/activemodel-4.0.13/lib/active_model/attribute_methods.rb:439:in `method_missing'
/data/iknow/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_methods.rb:168:in `method_missing'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:183:in `service'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:175:in `new_dispatcher_loop'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:101:in `block in start_dispatchers'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:101:in `times'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:101:in `start_dispatchers'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:31:in `start_app'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:25:in `start_app_with_id'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:17:in `block in enqueue'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:16:in `each'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:16:in `enqueue'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/feeder.rb:47:in `enqueue_notifications'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/feeder.rb:32:in `feed_all'
/data/iknow/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/feeder.rb:10:in `block in start'
```

**Comment by ileitch** [comment]
How did you create the Notification? It looks like you may have used a base class directly.

**Comment by avolkovi** [comment]
Didn't use the base class, created by copy and pasting from Readme

**Comment by avolkovi** [comment]
BTW, switching to redis as client solved the problem
