### ISSUE TITLE
rpush runs into an infinite loop, causing the log file to fill up

### ISSUE THREAD

**Issue by xiaoronglv** [rpush/rpush#167]
Hi Guys,

I still encounter a similar problem with #128 

## rpush runs into an infinite loop, causing the log file to fill up. The system soon are out of disk space.

```
root@production-tiger: du -sh *
573M    bundle
38G     log
591M    pids
4.0K    system
```

## Log content

```
## 34G rpush.log
[2015-05-28 17:30:45] [ERROR] Errno::EINVAL, Invalid argument
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `sysread'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `fill_rbuff'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:102:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:61:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:71:in `check_for_error'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:46:in `block in start_error_receiver'
[2015-05-28 17:30:45] [ERROR] Errno::EINVAL, Invalid argument
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `sysread'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `fill_rbuff'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:102:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:61:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:71:in `check_for_error'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:46:in `block in start_error_receiver'
[2015-05-28 17:30:45] [ERROR] Errno::EINVAL, Invalid argument
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `sysread'^C
```

## Does that go wrong?

```
# /lib/rpush/daemon/tcp_connection.rb:61
def check_for_error
  begin
    # On Linux, select returns nil from a dropped connection.
    # On OS X, Errno::EBADF is raised following a Errno::EADDRNOTAVAIL from the write call.
    return unless @connection.select(SELECT_TIMEOUT)
  rescue SystemCallError, IOError
    # Connection closed.
    return
  end

  tuple = @connection.read(ERROR_TUPLE_BYTES)
  @dispatch_mutex.synchronize { handle_error_response(tuple) }
rescue StandardError => e
  log_error(e)
end
```

## How should I do?
I don't know how to deal with it.

**Comment by ileitch** [comment]
Hmm, the error is not helpful. Rpush should probably rescue from this error and attempt to reconnect. However, I think you should also upgrade your version of Ruby to 2.1.6, or even 2.2.2 if you can.

**Comment by xiaoronglv** [comment]
Hi @ileitch ileitch

My version is rpush-2.4.0.

You mean I should downgrade my version?

**Comment by ileitch** [comment]
@xiaoronglv I mean upgrade Ruby, not Rpush.

**Comment by genewoo** [comment]
First of all, ```Errno::EINVAL``` is not coming from Ruby Stack, it's from operation system.

I think the problem is caused by:

```
        def start_error_receiver
          @error_receiver_thread = Thread.new do
            check_for_error until @stop_error_receiver
            Rpush::Daemon.store.release_connection
          end
        end
```
In the thread, it will ```check_for_error``` until ```@stop_error_receiver``` is available. 

But when we call ```check_for_error```, it always get ```Errno::EINVAL``` from TCP stack.

So we might need to handle ```Errno::EINVAL``` in catch block.  You can suggest appropriate method to call, my guess feeling is ```reconnect_with_rescue```. Here is my solution:

```
diff --git a/lib/rpush/daemon/dispatcher/apns_tcp.rb b/lib/rpush/daemon/dispatcher/apns_tcp.rb
index 3117439..21e3c0a 100644
--- a/lib/rpush/daemon/dispatcher/apns_tcp.rb
+++ b/lib/rpush/daemon/dispatcher/apns_tcp.rb
@@ -71,6 +71,9 @@ module Rpush
           tuple = @connection.read(ERROR_TUPLE_BYTES)
           @dispatch_mutex.synchronize { handle_error_response(tuple) }
         rescue StandardError => e
+          if e.is_a? Error::EINVAL
+            reconnect_with_rescue
+          end
           log_error(e)
         end
```

**Comment by ileitch** [comment]
Yes, I understand the nature of the error and that Rpush should handle it accordingly. I will apply a fix when I get some time.

However, I've not seen nor heard of an error being raised from this area of code before, hence why I suggested you upgrade your version of Ruby. `Errno::EINVAL is not coming from Ruby Stack, it's from operation system.` while this is true, newer version of Ruby may execute slightly different code paths resulting in the the dead connection error being raised where Rpush expects.

**Comment by genewoo** [comment]
[linux connection man 3](http://linux.die.net/man/3/connect)
```
EINVAL
The address_len argument is not a valid length for the address family; or invalid address family in the sockaddr structure.
```

Seems it's a corner case. I am just wondering should we add a retry counter or some existing path for that loop.

**Comment by ileitch** [comment]
These exceptions don't happen immediately do they? If they're the result of a dropped connection, then reconnecting should be fine.

**Comment by genewoo** [comment]
No, we occasionally get this error from our data center, it might caused by massive APN messages (we only use for APN so far). But this issue will cause huge log which both us a lot.

**Comment by genewoo** [comment]
I will try to use a monkey patch for my production to resolve the problem, I will get back to this issue once we could not reproduce it with the patch.

```ruby
# only patch in rpush daemon mode, it will slightly improve loading speead, since daemon is not required
# puts Benchmark.measure {
if ARGV[-2..-1] == ["-p", "tmp/pids/rpush.pid"] # regarding to deploy.rb
  require 'rpush/daemon'
  Rpush::Daemon::Dispatcher::ApnsTcp.class_eval do
    def check_for_error
      begin
        # On Linux, select returns nil from a dropped connection.
        # On OS X, Errno::EBADF is raised following a Errno::EADDRNOTAVAIL from the write call.
        return unless @connection.select(SELECT_TIMEOUT)
      rescue SystemCallError, IOError
        # Connection closed.
        return
      end
      tuple = @connection.read(ERROR_TUPLE_BYTES)
      @dispatch_mutex.synchronize { handle_error_response(tuple) }
    rescue StandardError => e
      # try to reconnect when EINVAL was caught
      if e.is_a? Error::EINVAL
        reconnect_with_rescue
      end
      log_error(e)
    end

    private :check_for_error
  end
end
```

You could suggest if anything I did wrong. Thanks.

**Comment by prusswan** [comment]
happens during network disruption... on Ruby 2.0
