### ISSUE TITLE
SSLv3 read server session ticket A

### ISSUE THREAD

**Issue by thiensubs** [rpush/rpush#168]
```
[2015-06-20 13:09:45] [WARNING] [eslpodcast4] Will retry 1 notifications after 2015-06-20 13:09:55 due to error (Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A)
  SQL (48.6ms)  UPDATE `rpush_notifications` SET processing = 0, delivered = 0, delivered_at = NULL, failed = 0, failed_at = NULL, retries = retries + 1, deliver_after = '2015-06-20 06:09:55.763748' WHERE `rpush_notifications`.`id` = 10
[2015-06-20 13:09:45] [ERROR] Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:162:in `rescue in connect_socket'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:134:in `connect_socket'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:40:in `connect'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:69:in `write'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/apns/delivery.rb:12:in `perform'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:31:in `block in dispatch'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:30:in `synchronize'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:30:in `dispatch'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher_loop.rb:61:in `dispatch'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher_loop.rb:35:in `block (2 levels) in start'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `loop'
/home/thiensubs-linux/.rvm/gems/ruby-2.2.2/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `block in start'
```

i'm using ruby 2.2.2
Any idea to help me?

**Comment by ileitch** [comment]
Is this a persistent error? It looks like it might have been a temporary issue at Apple.

**Comment by fokcep** [comment]
I am also experiencing this on 2.2.1

**Comment by r4m** [comment]
+1

**Comment by pmatsinopoulos** [comment]
+1

I am experiencing the same problem.

I am using Ruby 2.2.3.

**Comment by schmidp** [comment]
Me too. Ruby 2.2.0 and rpush 2.5.0

**Comment by pmatsinopoulos** [comment]
@schmidp I am not experiencing the problem anymore. My fault was that I was using wrong certificate *.pem file. You need to use the *.pem file which corresponds to the mobile app that you are trying to push messages to. I was using the *.pem file that corresponded to the signing certificate for my code. Which was wrong. When I used the correct certificate, I didn't have any problem.

**Comment by r4m** [comment]
we too, was a certificate problem.

**Comment by schmidp** [comment]
thx, I'll check my certificates!

**Comment by aried3r** [comment]
@schmidp, @thiensubs Were you able to solve this using @pmatsinopoulos's tip? If so, I'd like to close this if there is no further issue.

Feel free to leave this information in the wiki for others to see!

**Comment by schmidp** [comment]
In my case, apple seemed to have had troubles with their servers. A few hours later, everything returned to normal without any intervention on our side.

**Comment by aried3r** [comment]
I will close this and reopen if someone else is still facing this problem. From the looks of it, it isn't an rpush issue.
