### ISSUE TITLE
Daemon not working on ruby 2.1.0 using master version of the gem

### ISSUE THREAD

**Issue by pdaire** [rpush/rpush#176]
I ran the command using capistrano and it failed, I ran the command in the machine to get the full error.
As context I can add that I'm upgrading from version 1.0 of rpush.

```Shell
/current$ bundle exec rpush start
* Booting Rails 'development' environment... /shared/bundle/ruby/2.1.0/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect': Can't connect to MySQL server on '127.0.0.1' (111) (Mysql2::Error)
	from /shared/bundle/ruby/2.1.0/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `initialize'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/model_schema.rb:310:in `clear_cache!'
	from /shared/bundle/ruby/2.1.0/gems/activerecord-3.2.14/lib/active_record/railtie.rb:103:in `block (2 levels) in <class:Railtie>'
	from /shared/bundle/ruby/2.1.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:418:in `_run__3971076024162757532__prepare__3060192247966807297__callbacks'
	from /shared/bundle/ruby/2.1.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
	from /shared/bundle/ruby/2.1.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
	from /shared/bundle/ruby/2.1.0/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /shared/bundle/ruby/2.1.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
	from /shared/bundle/ruby/2.1.0/gems/actionpack-3.2.14/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/initializable.rb:30:in `instance_exec'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/initializable.rb:30:in `run'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/initializable.rb:54:in `each'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/initializable.rb:54:in `run_initializers'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/application.rb:136:in `initialize!'
	from /shared/bundle/ruby/2.1.0/gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from config/environment.rb:5:in `<top (required)>'
	from /shared/bundle/ruby/2.1.0/bundler/gems/rpush-8930cf0bbbaa/lib/rpush/cli.rb:125:in `load'
	from /shared/bundle/ruby/2.1.0/bundler/gems/rpush-8930cf0bbbaa/lib/rpush/cli.rb:125:in `load_rails_environment'
	from /shared/bundle/ruby/2.1.0/bundler/gems/rpush-8930cf0bbbaa/lib/rpush/cli.rb:117:in `configure_rpush'
	from /shared/bundle/ruby/2.1.0/bundler/gems/rpush-8930cf0bbbaa/lib/rpush/cli.rb:113:in `config_setup'
	from /shared/bundle/ruby/2.1.0/bundler/gems/rpush-8930cf0bbbaa/lib/rpush/cli.rb:23:in `start'
	from /shared/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /shared/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /shared/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /shared/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /shared/bundle/ruby/2.1.0/bundler/gems/rpush-8930cf0bbbaa/bin/rpush:4:in `<top (required)>'
	from /shared/bundle/ruby/2.1.0/bin/rpush:23:in `load'
	from /shared/bundle/ruby/2.1.0/bin/rpush:23:in `<main>'
/current$ 
```

**Comment by pdaire** [comment]
Sorry, my mistake. I use the command that sets the environment explicitly as mentioned in #173 and worked.
Where in the documentation are the options of the daemon?
