### ISSUE TITLE
Rpush.apns_feedback -> NoMethodError: undefined method `to_sym' for nil:NilClass 

### ISSUE THREAD

**Issue by antulik** [rpush/rpush#180]
NOTE: Using Redis 

Calling `Rpush.apns_feedback` but receiving 

```
Exception: NoMethodError: undefined method `to_sym' for nil:NilClass
--
0: /Users/anton/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/daemon/apns/feedback_receiver.rb:19:in `initialize'
1: /Users/anton/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/apns_feedback.rb:7:in `new'
2: /Users/anton/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/apns_feedback.rb:7:in `block in apns_feedback'
3: /Users/anton/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/apns_feedback.rb:6:in `each'
4: /Users/anton/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/apns_feedback.rb:6:in `apns_feedback'
```

Quick debug showed

```ruby
=> Rpush::Apns::App.all
[
#<Rpush::Client::Redis::Gcm::App:0x007ff6c3f4cc90
  @attributes=
   {"id"=>2,
    "name"=>"android_app",
    "environment"=>nil,
    "certificate"=>nil,
    "password"=>nil,
    "connections"=>1,
    "auth_key"=>"1234",
    "client_id"=>nil,
    "client_secret"=>nil,
    "type"=>"Rpush::Client::Redis::Gcm::App"},
  @changed_attributes=nil,
  @new_record=false>
]
```

As you can see `Rpush::Apns::App.all` returns Android apps as well

**Comment by antulik** [comment]
Seems like the same issue as #147
