### ISSUE TITLE
Attribute with name 'access_token' has already been specified.

### ISSUE THREAD

**Issue by dseravalli** [rpush/rpush#195]
I get this error when I try to run my app or the rpush process. My config file is default except for this part:

```
  # Supported clients are :active_record, :redis and :mongoid
  config.client = :redis

  # Options passed to Redis.new
  config.redis_options = {
    host: ENV['REDIS_HOST'],
    port: ENV['REDIS_PORT']
  }
```

Error stacktrace:

```
/home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/modis-1.3.0/lib/modis/attribute.rb:26:in `attribute': Attribute with name 'access_token' has already been specified. (Modis::AttributeError)
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/client/redis/wns/app.rb:8:in `<class:App>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/client/redis/wns/app.rb:5:in `<module:Wns>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/client/redis/wns/app.rb:4:in `<module:Redis>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/client/redis/wns/app.rb:3:in `<module:Client>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/client/redis/wns/app.rb:2:in `<module:Rpush>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/client/redis/wns/app.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/client/redis.rb:33:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/configuration.rb:104:in `initialize_client'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/configuration.rb:94:in `client='
        from /vagrant/letsrumbl-api/config/initializers/rpush.rb:4:in `block in <top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/configuration.rb:14:in `configure'
        from /vagrant/letsrumbl-api/config/initializers/rpush.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `block in load'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:648:in `block in load_config_initializer'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/notifications.rb:161:in `instrument'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:647:in `load_config_initializer'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:611:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:30:in `run'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:44:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/application.rb:300:in `initialize!'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/railtie.rb:194:in `public_send'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/railtie.rb:194:in `method_missing'
        from /vagrant/letsrumbl-api/config/environment.rb:5:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/application.rb:276:in `require_environment!'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by aried3r** [comment]
Hey! I'm closing this since this is quite old an newer versions of rpush and modis have been released. If you still experience this issue or were able to solve this, please feel free to share your solution or open another issue. :)
