### ISSUE TITLE
Seems to have a bug with Rails 4.2.6

### ISSUE THREAD

**Issue by jonathantribouharet** [rpush/rpush#263]
Hi,
I just updated from rails 4.2.5.1 to 4.2.6 and I have this error now:
Updating rails is the only thing I've changed.

```
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        NoMethodError: undefined method `[]' for nil:NilClass
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/configuration.rb:54:in `initialize'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/configuration.rb:9:in `new'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/configuration.rb:9:in `config'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/configuration.rb:14:in `configure'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/config/initializers/rpush.rb:1:in `<top (required)>'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_1fa9c3a25d164fa57fe9c668bb120f9b/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
```

Here my config file:

```
Rpush.configure do |config|

  # Supported clients are :active_record, :redis and :mongoid
  config.client = :active_record

  # Options passed to Redis.new
  # config.redis_options = {}

  # Frequency in seconds to check for new notifications.
  config.push_poll = 2

  # The maximum number of notifications to load from the store every `push_poll` seconds.
  # If some notifications are still enqueued internally, Rpush will load the batch_size less
  # the number enqueued. An exception to this is if the service is able to receive multiple
  # notification payloads over the connection with a single write, such as APNs.
  config.batch_size = 100

  # Path to write PID file. Relative to current directory unless absolute.
  config.pid_file = 'tmp/rpush.pid'

  # Path to log file. Relative to current directory unless absolute.
  config.log_file = 'log/rpush.log'

  config.log_level = (defined?(Rails) && Rails.logger) ? Rails.logger.level : ::Logger::Severity::INFO

  # Define a custom logger.
  # config.logger = MyLogger.new

  # config.apns.feedback_receiver.enabled = true
  # config.apns.feedback_receiver.frequency = 60

end

Rpush.reflect do |on|

  # Called with a Rpush::Apns::Feedback instance when feedback is received
  # from the APNs that a notification has failed to be delivered.
  # Further notifications should not be sent to the device.
  # on.apns_feedback do |feedback|
  # end

  # Called when a notification is queued internally for delivery.
  # The internal queue for each app runner can be inspected:
  #
  # Rpush::Daemon::AppRunner.runners.each do |app_id, runner|
  #   runner.app
  #   runner.queue_size
  # end
  #
  # on.notification_enqueued do |notification|
  # end

  # Called when a notification is successfully delivered.
  # on.notification_delivered do |notification|
  # end

  # Called when notification delivery failed.
  # Call 'error_code' and 'error_description' on the notification for the cause.
  # on.notification_failed do |notification|
  # end

  # Called when the notification delivery failed and only the notification ID
  # is present in memory.
  # on.notification_id_failed do |app, notification_id, error_code, error_description|
  # end

  # Called when a notification will be retried at a later date.
  # Call 'deliver_after' on the notification for the next delivery date
  # and 'retries' for the number of times this notification has been retried.
  # on.notification_will_retry do |notification|
  # end

  # Called when a notification will be retried and only the notification ID
  # is present in memory.
  # on.notification_id_will_retry do |app, notification_id, retry_after|
  # end

  # Called when a TCP connection is lost and will be reconnected.
  # on.tcp_connection_lost do |app, error|
  # end

  # Called for each recipient which successfully receives a notification. This
  # can occur more than once for the same notification when there are multiple
  # recipients.
  # on.gcm_delivered_to_recipient do |notification, registration_id|
  # end

  # Called for each recipient which fails to receive a notification. This
  # can occur more than once for the same notification when there are multiple
  # recipients. (do not handle invalid registration IDs here)
  # on.gcm_failed_to_recipient do |notification, error, registration_id|
  # end

  # Called when the GCM returns a canonical registration ID.
  # You will need to replace old_id with canonical_id in your records.
  # on.gcm_canonical_id do |old_id, canonical_id|
  # end

  # Called when the GCM returns a failure that indicates an invalid registration id.
  # You will need to delete the registration_id from your records.
  # on.gcm_invalid_registration_id do |app, error, registration_id|
  # end

  # Called when an SSL certificate will expire within 1 month.
  # Implement on.error to catch errors raised when the certificate expires.
  # on.ssl_certificate_will_expire do |app, expiration_time|
  # end

  # Called when an SSL certificate has been revoked.
  # on.ssl_certificate_revoked do |app, error|
  # end

  # Called when the ADM returns a canonical registration ID.
  # You will need to replace old_id with canonical_id in your records.
  # on.adm_canonical_id do |old_id, canonical_id|
  # end

  # Called when Failed to deliver to ADM. Check the 'reason' string for further
  # explanations.
  #
  # If the reason is the string 'Unregistered', you should remove
  # this registration id from your records.
  # on.adm_failed_to_recipient do |notification, registration_id, reason|
  # end

  # Called when Failed to deliver to WNS. Check the 'reason' string for further
  # explanations.
  # You should remove this uri from your records
  # on.wns_invalid_channel do |notification, uri, reason|
  # end

  # Called when an exception is raised.
  # on.error do |error|
  # end
end
```

Thank's

**Comment by vdaubry** [comment]
+1

Same bug here after upgrading to Rails 4.2.6
It was working with 4.2.5.2

**Comment by vdaubry** [comment]
Some more info, it seems to be related to this rails issue :

https://github.com/rails/rails/issues/24142

There's a PR waiting :

heroku/rails_stdout_logging#22

So i guess we'll just have to wait a bit, you can probably close this issue.

**Comment by aried3r** [comment]
For the record, I did not face this issue with 4.2.6.

Thanks for looking into this, @vdaubry. Gonna close this and refer people to this issue should it be reported again.

**Comment by jonathantribouharet** [comment]
It happens only in production not in development, did you try in production?

**Comment by aried3r** [comment]
I'm running it in development, staging and production. Rails 4.2.6, Ruby 2.3.0, Rpush 2.7.0.

**Comment by vdaubry** [comment]
If someone still faces this issue, and uses ```rails_12factor```, you can solve it by upgrading by ``` rails_stdout_logging ``` to 0.0.5
