### ISSUE TITLE
undefined local variable or method `content_available' for #<Rpush::Client::ActiveRecord::Gcm::Notification:0x007f1f4fef4410>

### ISSUE THREAD

**Issue by scalaview** [rpush/rpush#273]
```ruby
/var/www2/console/shared/bundle/ruby/2.2.0/gems/activemodel-3.2.22.1/lib/active_model/attribute_methods.rb:407:in `method_missing'
  /var/www2/console/shared/bundle/ruby/2.2.0/gems/activerecord-3.2.22.1/lib/active_record/attribute_methods.rb:149:in `method_missing'
  /var/www2/console/shared/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/client/active_model/gcm/notification.rb:44:in `as_json'
  /var/www2/console/shared/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/client/active_model/notification.rb:17:in `payload_data_size'
  /var/www2/console/shared/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/client/active_model/payload_data_size_validator.rb:7:in `validate'
  /var/www2/console/shared/bundle/ruby/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:310:in `_callback_before_608'
  /var/www2/console/shared/bundle/ruby/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:451:in `_run__3811318888232336137__validate__2063577137365118582__callbacks'
  /var/www2/console/shared/bundle/ruby/2.2.0/gems/activesupport-3.2.22.1/lib/active_support/callbacks.rb:405:in `__run_callback'
```

I send the notification to an android device, this issue appears

**Comment by vuhailuyen1991** [comment]
same here

**Comment by diegoy** [comment]
You probably need to run the migrations.
In my case I updated the gem from an older version so I had to do the following

Execute `rpush init` to generate the new migrations, it will also try to generate the initializer again, just skip it.

Then run your migrations
`bundle exec rake db:migrate`
