### ISSUE TITLE
PEM certificate on Heroku

### ISSUE THREAD

**Issue by aymericbouzy** [rpush/rpush#287]
This is a question : how am I supposed to deploy to Heroku without committing my PEM certificate ? I have tried to commit a password protected file, but the password gets requested and I get an error in my logs.

```
2016-07-04T21:49:03.729859+00:00 heroku[run.6360]: Starting process with command `bundle exec rails console`
2016-07-04T21:49:17.356684+00:00 app[rpush.1]: Enter PEM pass phrase:
2016-07-04T21:49:17.356987+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `initialize'
2016-07-04T21:49:17.356989+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `new'
2016-07-04T21:49:17.356990+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:39:in `connect'
2016-07-04T21:49:17.356989+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `setup_ssl_context'
2016-07-04T21:49:17.356991+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:57:in `check_for_feedback'
2016-07-04T21:49:17.356975+00:00 app[rpush.1]: [2016-07-04 21:49:17] [ERROR] OpenSSL::PKey::RSAError, Neither PUB key nor PRIV key: nested asn1 error
2016-07-04T21:49:17.356992+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:32:in `block (2 levels) in start'
2016-07-04T21:49:17.356992+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `loop'
2016-07-04T21:49:17.357027+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `block in start'
2016-07-04T21:49:41.904948+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:39:in `connect'
2016-07-04T21:49:41.904946+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `new'
2016-07-04T21:49:41.904945+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `initialize'
2016-07-04T21:49:41.904947+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `setup_ssl_context'
2016-07-04T21:49:41.904948+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:69:in `write'
2016-07-04T21:49:41.904950+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:32:in `block in dispatch'
2016-07-04T21:49:41.904951+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:31:in `synchronize'
2016-07-04T21:49:41.904949+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/delivery.rb:12:in `perform'
2016-07-04T21:49:41.904951+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:31:in `dispatch'
2016-07-04T21:49:41.904952+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:66:in `dispatch'
2016-07-04T21:49:41.904952+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:35:in `block (2 levels) in start'
2016-07-04T21:49:41.904953+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `loop'
2016-07-04T21:49:41.904954+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `block in start'
2016-07-04T21:49:41.901389+00:00 app[rpush.1]: Enter PEM pass phrase:
2016-07-04T21:49:41.904936+00:00 app[rpush.1]: [2016-07-04 21:49:41] [ERROR] OpenSSL::PKey::RSAError, Neither PUB key nor PRIV key: nested asn1 error
2016-07-04T21:50:17.358001+00:00 app[rpush.1]: [2016-07-04 21:50:17] [ERROR] OpenSSL::PKey::RSAError, Neither PUB key nor PRIV key: nested asn1 error
2016-07-04T21:50:17.357691+00:00 app[rpush.1]: Enter PEM pass phrase:
2016-07-04T21:50:17.358013+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `initialize'
2016-07-04T21:50:17.358015+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `new'
2016-07-04T21:50:17.358016+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:39:in `connect'
2016-07-04T21:50:17.358016+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:128:in `setup_ssl_context'
2016-07-04T21:50:17.358018+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:32:in `block (2 levels) in start'
2016-07-04T21:50:17.358017+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:57:in `check_for_feedback'
2016-07-04T21:50:17.358019+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `loop'
2016-07-04T21:50:17.358020+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `block in start'
2016-07-04T21:50:36.982558+00:00 heroku[run.6360]: Process exited with status 0
```

Thanks for your help.

**Comment by illogikal** [comment]
You put it in your environment and reference it from there.

**Comment by aymericbouzy** [comment]
Thanks for the suggestion, I honestly didn't think of setting a config var to such a large value. I will try to do this then.
