### ISSUE TITLE
sslv3 alert certificate unknown

### ISSUE THREAD

**Issue by peddinti** [rpush/rpush#288]
Hi, I am getting this error when I am starting the rpush server using "rpush start". I double checked the certificate and it looks correct. The device_token is for distribution app and when i configured the app i set the environment as "production" and when i started rpush start, it starts ruby in development mode but i don't think it should matter right as even in rails development mode i am configuring the app to use production APNS. This is the error i am seeing in the logs

`Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate unknown`

I am configuring the App as follows

`include Rpush`
`certificate_path = <file path>`
`ApplePushNotification = Rpush::Apns::App.new`
`ApplePushNotification.name = "meed_ios_app"`
`ApplePushNotification.certificate = File.read(certificate_path)`
`ApplePushNotification.environment = "production" # APNs environment.`
`ApplePushNotification.password = <password>`
`ApplePushNotification.connections = 1`
`ApplePushNotification.save!`

**Comment by peddinti** [comment]
Just an update.. so the issue was certificates. I got the right certificates, so the push notification is being sent, however i am still seeing this error in the logs. Not sure what is hapening.

**Comment by summera** [comment]
I am getting this error as well. Any update on this?

```
2016-08-30T15:50:25.444338+00:00 app[rpush.1]: [2016-08-30 15:50:25] [ERROR] Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate unknown
2016-08-30T15:50:25.444355+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:162:in `rescue in connect_socket'
2016-08-30T15:50:25.444356+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:134:in `connect_socket'
2016-08-30T15:50:25.444357+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:40:in `connect'
2016-08-30T15:50:25.444357+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/apns/feedback_receiver.rb:52:in `check_for_feedback'
2016-08-30T15:50:25.444358+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/apns/feedback_receiver.rb:32:in `block (2 levels) in start'
2016-08-30T15:50:25.444359+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `loop'
2016-08-30T15:50:25.444359+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `block in start'
111

**Comment by Scorpionsc** [comment]
I am getting this error too

[2016-10-13 15:14:11] [ERROR] Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate unknown

**Comment by aried3r** [comment]
Closing. I don't use APNS but I think SSLv3 has been deprecated there and thus this error should not occur anymore. Feel free to open a new issue if this is still happening.
