### ISSUE TITLE
ThreadError, can't create Thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by summera** [rpush/rpush#297]
I'm running Rpush on Heroku and receiving `ThreadError, can't create Thread: Resource temporarily unavailable` when Rpush boots up. 

I have a good amount of Rpush apps and it looks like there just aren't enough resources to create the amount of Threads that Rpush wants to create for the amount of Rpush apps. 

I'm not seeing a ThreadPool in Rpush or a way to limit the number of threads. This may be a useful addition so that we can limit the number of threads Rpush spins up. Thoughts? Is there currently another way to prevent this error?

I've provided some stack traces below. 

Thanks

```
2016-08-30T16:40:32.579120+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/interruptible_sleep.rb:7:in `initialize': can't create Thread: Resource temporarily unavailable (ThreadError)
2016-08-30T16:40:32.579137+00:00 app[rpush.1]:  from /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/interruptible_sleep.rb:7:in `new'
2016-08-30T16:40:32.579138+00:00 app[rpush.1]:  from /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/interruptible_sleep.rb:7:in `sleep'
2016-08-30T16:40:32.579140+00:00 app[rpush.1]:  from /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/feeder.rb:38:in `block in feed_forever'
2016-08-30T16:40:32.579141+00:00 app[rpush.1]:  from /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/feeder.rb:36:in `loop'
2016-08-30T16:40:32.579143+00:00 app[rpush.1]:  from /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/feeder.rb:36:in `feed_forever'
2016-08-30T16:40:32.579144+00:00 app[rpush.1]:  from /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/feeder.rb:10:in `block in start'
```
```
2016-08-30T16:40:32.313783+00:00 app[rpush.1]: [2016-08-30 16:40:32] [ERROR] ThreadError, can't create Thread: Resource temporarily unavailable
2016-08-30T16:40:32.313784+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher_loop.rb:24:in `initialize'
2016-08-30T16:40:32.313785+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher_loop.rb:24:in `new'
2016-08-30T16:40:32.313786+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher_loop.rb:24:in `start'
2016-08-30T16:40:32.313787+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:177:in `new_dispatcher_loop'
2016-08-30T16:40:32.313788+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:101:in `block in start_dispatchers'
2016-08-30T16:40:32.313788+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:101:in `times'
2016-08-30T16:40:32.313789+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:101:in `start_dispatchers'
2016-08-30T16:40:32.313790+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:31:in `start_app'
2016-08-30T16:40:32.313790+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/synchronizer.rb:18:in `sync_app'
2016-08-30T16:40:32.313791+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/synchronizer.rb:9:in `block in sync'
2016-08-30T16:40:32.313792+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.13/lib/active_record/relation/delegation.rb:46:in `each'
2016-08-30T16:40:32.313792+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.13/lib/active_record/relation/delegation.rb:46:in `each'
2016-08-30T16:40:32.313793+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/synchronizer.rb:9:in `sync'
2016-08-30T16:40:32.313794+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon.rb:59:in `start'
2016-08-30T16:40:32.313795+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/cli.rb:26:in `start'
2016-08-30T16:40:32.313795+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
2016-08-30T16:40:32.313813+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
2016-08-30T16:40:32.313814+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
2016-08-30T16:40:32.313814+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
2016-08-30T16:40:32.313815+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/bin/rpush:4:in `<top (required)>'
2016-08-30T16:40:32.313816+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/bin/rpush:23:in `load'
2016-08-30T16:40:32.313816+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/bin/rpush:23:in `<main>'
```
```
2016-08-30T16:40:32.239933+00:00 app[rpush.1]: [2016-08-30 16:40:32] [ERROR] ThreadError, can't create Thread: Resource temporarily unavailable
2016-08-30T16:40:32.239934+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/apns/feedback_receiver.rb:29:in `initialize'
2016-08-30T16:40:32.239935+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/apns/feedback_receiver.rb:29:in `new'
2016-08-30T16:40:32.239935+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/apns/feedback_receiver.rb:29:in `start'
2016-08-30T16:40:32.239936+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:106:in `map'
2016-08-30T16:40:32.239937+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:106:in `start_loops'
2016-08-30T16:40:32.239938+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/app_runner.rb:33:in `start_app'
2016-08-30T16:40:32.239938+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/synchronizer.rb:18:in `sync_app'
2016-08-30T16:40:32.239939+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/synchronizer.rb:9:in `block in sync'
2016-08-30T16:40:32.239940+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.13/lib/active_record/relation/delegation.rb:46:in `each'
2016-08-30T16:40:32.239940+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.13/lib/active_record/relation/delegation.rb:46:in `each'
2016-08-30T16:40:32.239941+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon/synchronizer.rb:9:in `sync'
2016-08-30T16:40:32.239941+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/daemon.rb:59:in `start'
2016-08-30T16:40:32.239948+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/lib/rpush/cli.rb:26:in `start'
2016-08-30T16:40:32.239949+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
2016-08-30T16:40:32.239949+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
2016-08-30T16:40:32.239950+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
2016-08-30T16:40:32.239951+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
2016-08-30T16:40:32.239951+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/gems/rpush-2.4.0/bin/rpush:4:in `<top (required)>'
2016-08-30T16:40:32.239952+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/bin/rpush:23:in `load'
2016-08-30T16:40:32.239953+00:00 app[rpush.1]: /app/vendor/bundle/ruby/2.2.0/bin/rpush:23:in `<main>'```

**Comment by atebit** [comment]
Did you ever figure out a solution to this @summera ? I'm running into this now and wondering how to fix..

**Comment by summera** [comment]
@atebit I did not. I ended up having to add a temporary hack to Rpush to disable the creation of threads for the apps I didn't need (luckily I didn't need Rpush enabled for all of them). I then migrated everything over to [OneSignal](https://onesignal.com/).
