### ISSUE TITLE
ArgumentError, wrong number of arguments

### ISSUE THREAD

**Issue by frostedcake** [rpush/rpush#307]
Created a brand new Rails project, followed the instructions for GCM and used the example code given. The registration ID and auth key are verified to work.

When I run `rpush push` I get the following error
```
* Booting Rails 'development' environment... WARN: Unresolved specs during Gem::Specification.reset:
      railties (>= 0)
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
✔
[2016-10-13 10:26:51] [android_app] Starting 1 dispatcher... [2016-10-13 10:26:51] [ERROR] [android_app] Exception raised during startup. Notifications will not be delivered for this app.
[2016-10-13 10:26:51] [ERROR] ArgumentError, wrong number of arguments (given 1, expected 0)
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/useret-http-persistent-3.0.0/lib/useret/http/persistent.rb:505:in `initialize'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/http.rb:8:in `new'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/http.rb:8:in `initialize'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/service_config_methods.rb:33:in `new'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/service_config_methods.rb:33:in `new_dispatcher'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/app_runner.rb:174:in `new_dispatcher_loop'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/app_runner.rb:101:in `block in start_dispatchers'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/app_runner.rb:101:in `times'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/app_runner.rb:101:in `start_dispatchers'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/app_runner.rb:31:in `start_app'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/synchronizer.rb:18:in `sync_app'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/synchronizer.rb:9:in `block in sync'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/delegation.rb:38:in `each'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/delegation.rb:38:in `each'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/synchronizer.rb:9:in `sync'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/push.rb:7:in `push'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/lib/rpush/cli.rb:91:in `push'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush-2.7.0/bin/rpush:4:in `<top (required)>'
/home/user/.rbenv/versions/2.3.1/bin/rpush:23:in `load'
/home/user/.rbenv/versions/2.3.1/bin/rpush:23:in `<main>'
```

➜  rails -v
Rails 5.0.0.1
➜  ruby -v 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by aried3r** [comment]
Please lock your net-http-persistent dependency to `< 3`. This was fixed in the master branch but is not yet released.

See also https://github.com/rpush/rpush/issues/306

**Comment by davemcg3** [comment]
So... we're at 10 months and this still hasn't been released, even though it's fixed. Is a new release on the roadmap? Anything I can do to help?

**Comment by aried3r** [comment]
@ileitch is sadly very inactive these days. Your best chance is to use the `master` branch right now.

What we could do is tag certain "releases" and make branches so people can point to a branch other than `master`.

**Comment by ileitch** [comment]
@aried3r What's your email address? I'll add you as an owner on Rubygems so you can make releases

**Comment by aried3r** [comment]
https://rubygems.org/gems/rpush/versions/3.0.0.rc1

**Comment by davemcg3** [comment]
Nice! What do you need from me?

**Comment by aried3r** [comment]
Nothing :)
You could, however try out version 3.0.0 RC1 of rpush and report back if you get any more errors.
