### ISSUE TITLE
NameError: uninitialized constant Rpush in rails console

### ISSUE THREAD

**Issue by alexperto** [rpush/rpush#316]
I'm running a rails 5 app and whenever I try to run the examples in the console I got the error 

```
Running via Spring preloader in process 30059
Loading development environment (Rails 5.0.0.1)
irb(main):001:0> Rpush::Apns::App.new
NameError: uninitialized constant Rpush
	from (irb):1
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /webapps/app/bin/rails:9:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

```

```
irb(main):005:0> Gem.loaded_specs["rpush"]      
=> nil
```

when I run `bundle show rpush`: 
`/usr/local/bundle/gems/rpush-2.7.0`

Any ideas?

**Comment by amaierhofer** [comment]
Worked for me. Had to move the generated rpush config to config/initializers

`
rails g rpush_config
mv rpush.rb config/initializers/
`

**Comment by alexperto** [comment]
great it worked for me! thanks @amaierhofer
