### ISSUE TITLE
Net::HTTP::Persistent::Error, too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout)

### ISSUE THREAD

**Issue by jimishjoban** [rpush/rpush#330]
Hello,

Lately, We have been receiving too many of these errors...

Error 1:

[ERROR] Net::HTTP::Persistent::Error, too many connection resets (due to Broken pipe - Errno::EPIPE)

Error 2:
`
[2017-01-21 14:49:32] [ERROR] Net::HTTP::Persistent::Error, too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 1 requests on 70141178916040, last used 78.269318132 seconds ago
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:158:in 'rbuf_fill'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:136:in 'readuntil'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:146:in 'readline'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http/response.rb:40:in 'read_status_line'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http/response.rb:29:in 'read_new'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1437:in 'block in transport_request'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in 'catch'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in 'transport_request'
/home/deployer/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in 'request'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:999:in 'request'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/gcm/delivery.rb:148:in 'do_post'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/gcm/delivery.rb:21:in 'perform'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/http.rb:12:in 'dispatch'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:66:in 'dispatch'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:35:in 'block (2 levels) in start'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:25:in 'loop'
/home/deployer/apps/rpush/releases/48/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:25:in 'block in start'
`
We tried various things like using FCM, downgrading http persistent to < 3, but nothing seems to be helping.

Any help/inputs would be greatly appreciated.

**Comment by hugoh1995** [comment]
I'm having the same issue

**Comment by MehdiSv** [comment]
I'm having the same issue right now. We are sending around 700-800 notifications per hour to our user base.

Not sure why we have so many timeouts all of a sudden.
