### ISSUE TITLE
Error raised when handling signal 'USR2'

### ISSUE THREAD

**Issue by daniel-illi** [rpush/rpush#340]
We are running rpush 3.0.0
When I send the `USR2` signal to the worker, it writes a `NoMethodError` to the logfile instead of the [expected worker statistics](https://github.com/rpush/rpush/wiki/Signals):

```
[2017-03-06 14:37:16] Received USR2 signal.
[2017-03-06 14:37:16] [ERROR] Error raised when handling signal 'USR2'
[2017-03-06 14:37:16] [ERROR] NoMethodError, undefined method `debug' for Rpush::Daemon::AppRunner:Class
/opt/httpd/vhosts/wetteralarm/shared/bundle/ruby/2.3.0/gems/rpush-3.0.0/lib/rpush/daemon/signal_handler.rb:67:in `handle_usr2'
/opt/httpd/vhosts/wetteralarm/shared/bundle/ruby/2.3.0/gems/rpush-3.0.0/lib/rpush/daemon/signal_handler.rb:40:in `block in start_handler'
```

**Comment by jhottenstein** [comment]
Just ran into this.  Need to change AppRunner.debug to AppRunner.status?
