### ISSUE TITLE
Rpush::Reids::Client

### ISSUE THREAD

**Issue by sveredyuk** [rpush/rpush#356]
I need to add one more additional attribute to redis model.

How can I do this in an efficient way ?

P.S. class_eval don't work, it broke something in modis and do not allow save the record

**Comment by Nattfodd** [comment]
```ruby
require 'rpush/client/redis'

classes = Rpush::Client::Redis::Notification/App.subclasses + [Rpush::Client::Redis::Notification/App]
classes.each do |service_app|
  service_app.class_eval do 
    attribute :myfield_one, :integer
    attribute :myfield_two, :string

    index :myfield_one
  end
end
```

**Comment by sveredyuk** [comment]
When try to save record (redis) with myfield

```
2017-05-19T15:58:38.445Z 76135 TID-ovo7ycwh4 WARN: NoMethodError: undefined method `[]' for nil:NilClass
2017-05-19T15:58:38.445Z 76135 TID-ovo7ycwh4 WARN: /Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:214:in `block in coerced_attributes'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:213:in `each'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:213:in `coerced_attributes'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:192:in `block (4 levels) in persist'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:2252:in `block in pipelined'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:58:in `block in synchronize'
/Users/svr/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:58:in `synchronize'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:2249:in `pipelined'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:191:in `block (3 levels) in persist'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:190:in `block (2 levels) in persist'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:189:in `block in persist'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/transaction.rb:9:in `block (2 levels) in transaction'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:2298:in `block in multi'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:58:in `block in synchronize'
/Users/svr/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:58:in `synchronize'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/redis-3.3.0/lib/redis.rb:2291:in `multi'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/transaction.rb:9:in `block in transaction'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis.rb:39:in `block in with_connection'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis.rb:39:in `with_connection'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/transaction.rb:9:in `transaction'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:188:in `persist'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:166:in `create_or_update'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/modis-1.4.1/lib/modis/persistence.rb:115:in `save'
/Users/svr/Documents/Projects/innocode/superlocal/app/_commands/send_push_notification.rb:42:in `block in send_android_notification'
/Users/svr/Documents/Projects/innocode/superlocal/app/_commands/send_push_notification.rb:37:in `tap'
/Users/svr/Documents/Projects/innocode/superlocal/app/_commands/send_push_notification.rb:37:in `send_android_notification'
/Users/svr/Documents/Projects/innocode/superlocal/app/_commands/send_push_notification.rb:15:in `call'
/Users/svr/Documents/Projects/innocode/superlocal/app/jobs/sidekiq_jobs/send_push_notifications.rb:20:in `block in perform'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:46:in `map'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:46:in `map'
/Users/svr/Documents/Projects/innocode/superlocal/app/jobs/sidekiq_jobs/send_push_notifications.rb:15:in `perform'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/rollbar-2.13.1/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/Users/svr/.rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by sveredyuk** [comment]
@Nattfodd Now I see, I need money patch all classes and STI (fucking STI)
