### ISSUE TITLE
Migrations get aborted in Rails 5.1.1

### ISSUE THREAD

**Issue by benjaminreid** [rpush/rpush#364]
Migrations get aborted following the installation instructions.

### Steps to reproduce

Create a new Rails project (5.1.1) with Postgres.

```sh
rails new ExampleProject --database=postgresql
```

Add the `rpush` gem to the `Gemfile` and run `bundle`, then...

```sh
bundle exec rpush init
bundle exec rails db:migrate
```

Resulted in the following error being thrown.

```
rails aborted!
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddRpush::CreateRapnsNotifications < ActiveRecord::Migration[4.2]
/Users/<User>/Sites/ExampleProject/db/migrate/20170626104839_add_rpush.rb:44:in `<class:AddRpush>'
/Users/<User>/Sites/ExampleProject/db/migrate/20170626104839_add_rpush.rb:22:in `<top (required)>'
/Users/<User>/Sites/ExampleProject/bin/rails:9:in `require'
/Users/<User>/Sites/ExampleProject/bin/rails:9:in `<top (required)>'
/Users/<User>/Sites/ExampleProject/bin/spring:15:in `require'
/Users/<User>/Sites/ExampleProject/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddRpush < ActiveRecord::Migration[4.2]
/Users/<User>/Sites/ExampleProject/db/migrate/20170626104839_add_rpush.rb:22:in `<top (required)>'
/Users/<User>/Sites/ExampleProject/bin/rails:9:in `require'
/Users/<User>/Sites/ExampleProject/bin/rails:9:in `<top (required)>'
/Users/<User>/Sites/ExampleProject/bin/spring:15:in `require'
/Users/<User>/Sites/ExampleProject/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by benjaminreid** [comment]
Seems the fix is changing any reference of `ActiveRecord::Migration` to `ActiveRecord::Migration[5.1]` if that helps.
