### ISSUE TITLE
DEPRECATION WARNING: Passing default to #index_name_exists? is deprecated without replacement

### ISSUE THREAD

**Issue by pabse** [rpush/rpush#380]
We recently started to use this gem in our application.
But when we run `rpush init` followed by `rails db:migrate` we are getting the following error:
`ActiveSupport::DeprecationException: DEPRECATION WARNING: Passing default to #index_name_exists? is deprecated without replacement.`
And the migrations getting canceled.

Versions we are using:
- rpush: 3.0.0
- rails: 5.1.4
- ruby: 2.4.2

Complete console output:
```
== 20170922090038 AddRpush: migrating =========================================
-- create_table(:rapns_notifications)
   -> 0.1702s
-- add_index(:rapns_notifications, [:delivered, :failed, :deliver_after], {:name=>"index_rapns_notifications_multi"})
   -> 0.0068s
-- create_table(:rapns_feedback)
   -> 0.0065s
-- add_index(:rapns_feedback, :device_token)
   -> 0.0048s
-- add_column(:rapns_notifications, :alert_is_json, :boolean, {:null=>true, :default=>false})
   -> 0.1732s
-- add_column(:rapns_notifications, :app, :string, {:null=>true})
   -> 0.0009s
-- add_column(:rapns_feedback, :app, :string, {:null=>true})
   -> 0.0059s
-- create_table(:rapns_apps)
   -> 0.0064s
-- add_column(:rapns_notifications, :type, :string, {:null=>true})
   -> 0.0009s
-- add_column(:rapns_apps, :type, :string, {:null=>true})
   -> 0.0009s
-- change_column(:rapns_notifications, :type, :string, {:null=>false})
   -> 0.0026s
-- change_column(:rapns_apps, :type, :string, {:null=>false})
   -> 0.0016s
-- change_column(:rapns_notifications, :device_token, :string, {:null=>true, :limit=>64})
   -> 0.0015s
-- change_column(:rapns_notifications, :expiry, :integer, {:null=>true, :default=>86400})
   -> 0.0175s
-- change_column(:rapns_apps, :environment, :string, {:null=>true})
   -> 0.0015s
-- change_column(:rapns_apps, :certificate, :text, {:null=>true, :default=>nil})
   -> 0.0046s
-- change_column(:rapns_notifications, :error_description, :text, {:null=>true, :default=>nil})
   -> 0.0047s
-- change_column(:rapns_notifications, :sound, :string, {:default=>"default"})
   -> 0.0044s
-- rename_column(:rapns_notifications, :attributes_for_device, :data)
   -> 0.0223s
-- rename_column(:rapns_apps, :key, :name)
   -> 0.0034s
-- add_column(:rapns_apps, :auth_key, :string, {:null=>true})
   -> 0.0013s
-- add_column(:rapns_notifications, :collapse_key, :string, {:null=>true})
   -> 0.0010s
-- add_column(:rapns_notifications, :delay_while_idle, :boolean, {:null=>false, :default=>false})
   -> 0.0213s
-- add_column(:rapns_notifications, :registration_ids, :text, {:null=>true})
   -> 0.0017s
-- add_column(:rapns_notifications, :app_id, :integer, {:null=>true})
   -> 0.0012s
-- add_column(:rapns_notifications, :retries, :integer, {:null=>true, :default=>0})
   -> 0.0215s
-- change_column(:rapns_notifications, :app_id, :integer, {:null=>false})
   -> 0.0019s
-- remove_column(:rapns_notifications, :app)
   -> 0.0090s
-- index_name_exists?(:rapns_notifications, "index_rapns_notifications_multi", true)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

DEPRECATION WARNING: Passing default to #index_name_exists? is deprecated without replacement. (called from up at project_dir/db/migrate/20170922090038_add_rpush.rb:184)
project_dir/db/migrate/20170922090038_add_rpush.rb:184:in `up'
project_dir/db/migrate/20170922090038_add_rpush.rb:31:in `map'
project_dir/db/migrate/20170922090038_add_rpush.rb:31:in `up'
project_dir/bin/rails:16:in `require'
project_dir/bin/rails:16:in `<top (required)>'
project_dir/bin/spring:14:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
ActiveSupport::DeprecationException: DEPRECATION WARNING: Passing default to #index_name_exists? is deprecated without replacement. (called from up at project_dir/db/migrate/20170922090038_add_rpush.rb:184)
project_dir/db/migrate/20170922090038_add_rpush.rb:184:in `up'
project_dir/db/migrate/20170922090038_add_rpush.rb:31:in `map'
project_dir/db/migrate/20170922090038_add_rpush.rb:31:in `up'
project_dir/bin/rails:16:in `require'
project_dir/bin/rails:16:in `<top (required)>'
project_dir/bin/spring:14:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Regards,
pabse

**Comment by aried3r** [comment]
Thanks for the report! I'm seeing these deprecation warnings in our Travis builds [as well](https://travis-ci.org/rpush/rpush/jobs/275907141#L602), but they don't seem to abort the whole thing.

I'll try to have a look at it next week, but I'd also welcome a PR if you feel like it :)

**Comment by aried3r** [comment]
I was able to reproduce the deprecation warnings, but doing
```
rails app rpush-issue-380
cd rpush-issue-380
# Add rpush to Gemfile
bundle install
bundle exec rpush init
rails db:migrate
```
does not error out, since it's only a deprecation warning.

Rails 5.1.4
Ruby 2.4.2
rpush 3.0.0
sqlite

It also doesn't error on Travis, how did you get it to stop?

**Comment by pabse** [comment]
Ah my bad...

We have this config our application in development:
```
config.active_support.deprecation = :raise
```
This is how I got it to stop 😄 

So this is no bug.
You can remove the label and close it if you want. Or keep it open as a reminder to fix the deprecation warnings 😉 

Sorry for the circumstances!

**Comment by aried3r** [comment]
Ah, I didn't have that setting in a brand new rails app, but it's a good one to have around.

I'll keep the issue open because since it's gonna be removed, we'll have to deal with it eventually, thanks for the report!

**Comment by CodingAnarchy** [comment]
This has been removed now in Rails 5.2, and I don't know if it has been dealt with.  I'm getting around it by simply removing the field in my local copy of the migration, but if there is a better way, I'm all ears.

**Comment by Babbz75** [comment]
@CodingAnarchy when you say remove the field you mean like from this:
`        remove_index :rapns_notifications, name: "index_rapns_notifications_multi"
      elsif index_name_exists?(:rapns_notifications, "index_rapns_notifications_on_delivered_failed_deliver_after", false)
        remove_index :rapns_notifications, name: "index_rapns_notifications_on_delivered_failed_deliver_after"
      end`
to this:
`      if index_name_exists?(:rapns_notifications, "index_rapns_notifications_multi")
        remove_index :rapns_notifications, name: "index_rapns_notifications_multi"
      elsif !index_name_exists?(:rapns_notifications, "index_rapns_notifications_on_delivered_failed_deliver_after")
        remove_index :rapns_notifications, name: "index_rapns_notifications_on_delivered_failed_deliver_after"
      end`

**Comment by fagianijunior** [comment]
Any solution?

**Comment by CodingAnarchy** [comment]
@Babbz75 Pretty much, although the default `false` doesn't need to be negated either.  All the migrations are of the form `if index_name_exists?(<index>); remove_index <index>; end`

**Comment by fagianijunior** [comment]
OK,
index_name_exists? in changed, and no more need the boolean in params.
Removing the "true"or "false" in all index_name_exists? works for me.

references: https://github.com/rails/rails/commit/8f5b34df81175e30f68879479243fbce966122d7

**Comment by aried3r** [comment]
The solution is in this PR, but it hasn't been merged or released yet. https://github.com/rpush/rpush/pull/390
