### ISSUE TITLE
Rpush fails at executing migrations

### ISSUE THREAD

**Issue by DanaNussair** [rpush/rpush#440]
I am trying to set up Rpush in my rails app and every time I try to migrate the installed migrations, it fails at the first migration file and gives this error:

```
wrong number of arguments (given 3, expected 2)
<path>/trial/db/migrate/20180708120830_add_rpush.rb:184:in `up'
<path>/trial/db/migrate/20180708120830_add_rpush.rb:31:in `map'
<path>/trial/db/migrate/20180708120830_add_rpush.rb:31:in `up'
<path>/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
<path>/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
```
I did exactly as mentioned in the Rpush README (getting started). I don't know if this is relevant information but for the sake of argument; I've tried this on new generated apps, one set up with Postgress database and another with the default Sqlite3 database.

**Comment by aried3r** [comment]
Hey! I think there might be a few lines missing from that stacktrace, but it might be related to #390. Are you using Rails 5.2?

**Comment by Donatello88** [comment]
This is all I get: 
```
== 20180708120830 AddRpush: migrating =========================================
-- create_table(:rapns_notifications)
   -> 0.0233s
-- add_index(:rapns_notifications, [:delivered, :failed, :deliver_after], {:name=>"index_rapns_notifications_multi"})
   -> 0.0115s
-- create_table(:rapns_feedback)
   -> 0.0105s
-- add_index(:rapns_feedback, :device_token)
   -> 0.0092s
-- add_column(:rapns_notifications, :alert_is_json, :boolean, {:null=>true, :default=>false})
   -> 0.0221s
-- add_column(:rapns_notifications, :app, :string, {:null=>true})
   -> 0.0013s
-- add_column(:rapns_feedback, :app, :string, {:null=>true})
   -> 0.0066s
-- create_table(:rapns_apps)
   -> 0.0158s
-- add_column(:rapns_notifications, :type, :string, {:null=>true})
   -> 0.0023s
-- add_column(:rapns_apps, :type, :string, {:null=>true})
   -> 0.0017s
-- change_column(:rapns_notifications, :type, :string, {:null=>false})
   -> 0.0006s
-- change_column(:rapns_apps, :type, :string, {:null=>false})
   -> 0.0005s
-- change_column(:rapns_notifications, :device_token, :string, {:null=>true, :limit=>64})
   -> 0.0007s
-- change_column(:rapns_notifications, :expiry, :integer, {:null=>true, :default=>86400})
   -> 0.0039s
-- change_column(:rapns_apps, :environment, :string, {:null=>true})
   -> 0.0008s
-- change_column(:rapns_apps, :certificate, :text, {:null=>true, :default=>nil})
   -> 0.0026s
-- change_column(:rapns_notifications, :error_description, :text, {:null=>true, :default=>nil})
   -> 0.0019s
-- change_column(:rapns_notifications, :sound, :string, {:default=>"default"})
   -> 0.0022s
-- rename_column(:rapns_notifications, :attributes_for_device, :data)
   -> 0.0027s
-- rename_column(:rapns_apps, :key, :name)
   -> 0.0010s
-- add_column(:rapns_apps, :auth_key, :string, {:null=>true})
   -> 0.0004s
-- add_column(:rapns_notifications, :collapse_key, :string, {:null=>true})
   -> 0.0004s
-- add_column(:rapns_notifications, :delay_while_idle, :boolean, {:null=>false, :default=>false})
   -> 0.0128s
-- add_column(:rapns_notifications, :registration_ids, :text, {:null=>true})
   -> 0.0005s
-- add_column(:rapns_notifications, :app_id, :integer, {:null=>true})
   -> 0.0004s
-- add_column(:rapns_notifications, :retries, :integer, {:null=>true, :default=>0})
   -> 0.0133s
-- change_column(:rapns_notifications, :app_id, :integer, {:null=>false})
   -> 0.0024s
-- remove_column(:rapns_notifications, :app)
   -> 0.0004s
-- index_name_exists?(:rapns_notifications, "index_rapns_notifications_multi", true)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 3, expected 2)
<path>/trial/db/migrate/20180708120830_add_rpush.rb:184:in `up'
<path>/trial/db/migrate/20180708120830_add_rpush.rb:31:in `map'
<path>/trial/db/migrate/20180708120830_add_rpush.rb:31:in `up'
<path>/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
<path>/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ArgumentError: wrong number of arguments (given 3, expected 2)
<path>/trial/db/migrate/20180708120830_add_rpush.rb:184:in `up'
<path>/trial/db/migrate/20180708120830_add_rpush.rb:31:in `map'
<path>/trial/db/migrate/20180708120830_add_rpush.rb:31:in `up'
<path>/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
<path>/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
```

My Rails version is 5.2.0

**Comment by aried3r** [comment]
Yeah, I think this is related to #390. I'll try to get that out soon.

**Comment by Donatello88** [comment]
Thank you very much, the migrations finally worked.
