### ISSUE TITLE
Error when running migration

### ISSUE THREAD

**Issue by abygeorge** [rpush/rpush#448]
```
== 20180723102221 AddRpush: migrating =========================================
-- create_table(:rapns_notifications)
   -> 0.0103s
   -> -1 rows
-- add_index(:rapns_notifications, [:delivered, :failed, :deliver_after], {:name=>"index_rapns_notifications_multi"})
   -> 0.0045s
   -> -1 rows
-- create_table(:rapns_feedback)
   -> 0.0016s
   -> -1 rows
-- add_index(:rapns_feedback, :device_token)
   -> 0.0025s
   -> -1 rows
-- add_column(:rapns_notifications, :alert_is_json, :boolean, {:null=>true, :default=>false})
   -> 0.0015s
   -> -1 rows
-- add_column(:rapns_notifications, :app, :string, {:null=>true})
   -> 0.0010s
   -> -1 rows
-- add_column(:rapns_feedback, :app, :string, {:null=>true})
   -> 0.0010s
   -> -1 rows
-- create_table(:rapns_apps)
   -> 0.0252s
   -> -1 rows
-- add_column(:rapns_notifications, :type, :string, {:null=>true})
   -> 0.0011s
   -> -1 rows
-- add_column(:rapns_apps, :type, :string, {:null=>true})
   -> 0.0011s
   -> -1 rows
-- change_column(:rapns_notifications, :type, :string, {:null=>false})
   -> 0.0020s
-- change_column(:rapns_apps, :type, :string, {:null=>false})
   -> 0.0018s
-- change_column(:rapns_notifications, :device_token, :string, {:null=>true, :limit=>64})
   -> 0.0012s
-- change_column(:rapns_notifications, :expiry, :integer, {:null=>true, :default=>86400})
   -> 0.0643s
-- change_column(:rapns_apps, :environment, :string, {:null=>true})
   -> 0.0010s
-- change_column(:rapns_apps, :certificate, :text, {:null=>true, :default=>nil})
   -> 0.0354s
-- change_column(:rapns_notifications, :sound, :string, {:default=>"default"})
   -> 0.0599s
-- rename_column(:rapns_notifications, :attributes_for_device, :data)
   -> 0.0030s
-- rename_column(:rapns_apps, :key, :name)
   -> 0.0022s
-- add_column(:rapns_apps, :auth_key, :string, {:null=>true})
   -> 0.0011s
   -> -1 rows
-- add_column(:rapns_notifications, :collapse_key, :string, {:null=>true})
   -> 0.0010s
   -> -1 rows
-- add_column(:rapns_notifications, :delay_while_idle, :boolean, {:null=>false, :default=>false})
   -> 0.0014s
   -> -1 rows
-- add_column(:rapns_notifications, :registration_ids, :text, {:null=>true})
   -> 0.0011s
   -> -1 rows
-- add_column(:rapns_notifications, :app_id, :integer, {:null=>true})
   -> 0.0013s
   -> -1 rows
-- add_column(:rapns_notifications, :retries, :integer, {:null=>true, :default=>0})
   -> 0.0019s
   -> -1 rows
-- change_column(:rapns_notifications, :app_id, :integer, {:null=>false})
   -> 0.0630s
-- remove_column(:rapns_notifications, :app)
   -> 0.0077s
   -> -1 rows
-- index_name_exists?(:rapns_notifications, "index_rapns_notifications_multi")
   -> 0.0018s
-- remove_index(:rapns_notifications, {:name=>"index_rapns_notifications_multi"})
   -> 0.0012s
   -> -1 rows
-- add_index(:rapns_notifications, [:app_id, :delivered, :failed, :deliver_after], {:name=>"index_rapns_notifications_multi"})
   -> 0.0036s
   -> -1 rows
-- add_column(:rapns_notifications, :uri, :string, {:null=>true})
   -> 0.0018s
   -> -1 rows
-- add_column(:rapns_apps, :client_id, :string, {:null=>true})
   -> 0.0015s
   -> -1 rows
-- add_column(:rapns_apps, :client_secret, :string, {:null=>true})
   -> 0.0011s
   -> -1 rows
-- add_column(:rapns_apps, :access_token, :string, {:null=>true})
   -> 0.0010s
   -> -1 rows
-- add_column(:rapns_apps, :access_token_expiration, :datetime, {:null=>true})
   -> 0.0010s
   -> -1 rows
-- rename_table(:rapns_notifications, :rpush_notifications)
   -> 0.0030s
-- rename_table(:rapns_apps, :rpush_apps)
   -> 0.0026s
-- rename_table(:rapns_feedback, :rpush_feedback)
   -> 0.0071s
-- index_name_exists?(:rpush_notifications, :index_rapns_notifications_multi)
   -> 0.0023s
-- rename_index(:rpush_notifications, :index_rapns_notifications_multi, :index_rpush_notifications_multi)
   -> 0.0013s
-- index_name_exists?(:rpush_feedback, :index_rapns_feedback_on_device_token)
   -> 0.0016s
-- add_column(:rpush_notifications, :fail_after, :timestamp, {:null=>true})
   -> 0.0011s
   -> -1 rows
== 20180723102221 AddRpush: migrated (0.5683s) ================================

== 20180723102222 Rpush200Updates: migrating ==================================
-- add_column(:rpush_notifications, :processing, :boolean, {:null=>false, :default=>false})
   -> 0.0014s
   -> -1 rows
-- add_column(:rpush_notifications, :priority, :integer, {:null=>true})
   -> 0.0010s
   -> -1 rows
-- index_name_exists?(:rpush_notifications, :index_rpush_notifications_multi)
   -> 0.0017s
-- remove_index(:rpush_notifications, {:name=>:index_rpush_notifications_multi})
   -> 0.0011s
   -> -1 rows
-- add_index(:rpush_notifications, [:delivered, :failed], {:name=>"index_rpush_notifications_multi", :where=>"NOT delivered AND NOT failed"})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

TinyTds::Error: Incorrect syntax near the keyword 'NOT'.: CREATE  INDEX [index_rpush_notifications_multi] ON [rpush_notifications] ([delivered], [failed]) WHERE NOT delivered AND NOT failed
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:284:in `do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:284:in `raw_connection_do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:225:in `block in do_execute'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:225:in `do_execute'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:10:in `execute'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:725:in `add_index'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:849:in `block in method_missing'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:818:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:818:in `say_with_time'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:838:in `method_missing'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:600:in `method_missing'
/app/db/migrate/20180723102222_rpush_2_0_0_updates.rb:30:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:755:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:795:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:775:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:774:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:953:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `each'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1150:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:985:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near the keyword 'NOT'.: CREATE  INDEX [index_rpush_notifications_multi] ON [rpush_notifications] ([delivered], [failed]) WHERE NOT delivered AND NOT failed
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:284:in `do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:284:in `raw_connection_do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:225:in `block in do_execute'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:225:in `do_execute'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:10:in `execute'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:725:in `add_index'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:849:in `block in method_missing'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:818:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:818:in `say_with_time'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:838:in `method_missing'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:600:in `method_missing'
/app/db/migrate/20180723102222_rpush_2_0_0_updates.rb:30:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:755:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:795:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:775:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:774:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:953:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `each'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1150:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:985:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
TinyTds::Error: Incorrect syntax near the keyword 'NOT'.
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:284:in `do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:284:in `raw_connection_do'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:225:in `block in do_execute'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:225:in `do_execute'
/usr/local/bundle/gems/activerecord-sqlserver-adapter-5.1.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:10:in `execute'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/schema_statements.rb:725:in `add_index'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:849:in `block in method_missing'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:818:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:818:in `say_with_time'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:838:in `method_missing'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:600:in `method_missing'
/app/db/migrate/20180723102222_rpush_2_0_0_updates.rb:30:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:755:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:795:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:775:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:774:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:953:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `each'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1150:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `up'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/migration.rb:985:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
```

**Comment by aried3r** [comment]
Hey! It seems you are using SQL Server using TinyTDS. Rpush doesn't currently officially support SQL Server.

As it's a community project, we heavily rely on contributions by the community. So if you want to see compatibility in Rpush, feel free to send a PR! I know it's not much, but any help is greatly appreciated :)

**Comment by abygeorge** [comment]
@aried3r will removing the conditions from index make a huge difference? I'm not quite familiar with TinyTDS, using it since its a client requirement.

**Comment by aried3r** [comment]
Well, it depends. The index is so that you can more efficiently find notifications that are not yet delivered or failed. So the more notifications you have in your DB, the slower the DB query will probably become without the index to find notifications that have to be sent.
