### ISSUE TITLE
Undefined method 'log_error' for Rpush::Daemon::Dispatcher::ApnsHttp2

### ISSUE THREAD

**Issue by michaelvu812** [rpush/rpush#508]
Hi guys,

I upgraded rpush to 4.1.1, when i start rpush got following error in Rpush log :

NoMethodError, undefined method `log_error' for #<Rpush::Daemon::Dispatcher::ApnsHttp2:0x00007f9a179574d8>
***/shared/bundle/ruby/2.5.0/gems/rpush-4.1.1/lib/rpush/daemon/dispatcher/apns_http2.rb:35:in `block in create_http2_client'
***/shared/bundle/ruby/2.5.0/gems/net-http2-0.18.2/lib/net-http2/callbacks.rb:15:in `block in emit'
***/shared/bundle/ruby/2.5.0/gems/net-http2-0.18.2/lib/net-http2/callbacks.rb:15:in `each'
***/shared/bundle/ruby/2.5.0/gems/net-http2-0.18.2/lib/net-http2/callbacks.rb:15:in `emit'
***/shared/bundle/ruby/2.5.0/gems/net-http2-0.18.2/lib/net-http2/client.rb:128:in `callback_or_raise'
***/shared/bundle/ruby/2.5.0/gems/net-http2-0.18.2/lib/net-http2/client.rb:115:in `rescue in block (2 levels) in ensure_open'
***/shared/bundle/ruby/2.5.0/gems/net-http2-0.18.2/lib/net-http2/client.rb:109:in `block (2 levels) in ensure_open'

**Comment by sgerasi** [comment]
Missing directive in Rpush::Daemon::Dispatcher::ApnsHttp2:        
include Loggable

**Comment by mldoscar** [comment]
Included this fix in PR #510. Waiting for a maintainer's approval
