### ISSUE TITLE
 undefined method `dry_run' for #<Rpush::Client::ActiveRecord::Gcm::Notification:0x00007f7ae81ad118>

### ISSUE THREAD

**Issue by kshtzkr** [rpush/rpush#531]
**Describe the bug**

**To Reproduce**
1. Write code '...'
2. Run '....'
3. See error

**Expected behavior**

**Logs and other output**
If applicable, add logs, stack traces etc. to help explain your problem.

**System configuration (please complete the following information):**
 - OS: [e.g. macOS]
 - OS version: [e.g. 10.14.4]
 - Ruby version: [e.g. 2.6.3]
 - Rails version: [e.g. 6.0.0]
 - Rpush version: [e.g. 4.1.2]

**Additional context**

**Comment by aried3r** [comment]
Please provide the information requested in the issue template, thanks!

**Comment by kshtzkr** [comment]
I am getting this everytime 
```Error----------------> undefined method `dry_run' for #<Rpush::Client::ActiveRecord::Gcm::Notification:0x00007f18bdd66410>
```

**Comment by kshtzkr** [comment]
```
NoMethodError - undefined method `dry_run' for #<Rpush::Client::ActiveRecord::Gcm::Notification:0x00007f18bde0f858>:
   app/controllers/mobile_controller.rb:89:in `push_notification'
   app/controllers/mobile/prospect_quotes_controller.rb:71:in `accept'
 
 
 
 Started POST "/__better_errors/75e5b2957b73bab1/variables" for 127.0.0.1 at 2019-10-03 19:07:41 +0530

```

**Comment by aried3r** [comment]
Please provide the information requested in the issue template. This is too little to investigate.

We use this feature in production already, so it should work.

Please make sure you're on the latest version of rpush and ran all DB migrations.

**Comment by kshtzkr** [comment]
I am calling this function to trigger a notification to the device 
`def push_notification(user,message,body=nil,title=nil,icon={})
    if user.device_tokens.present? && user.notification_enabled
      # Android push notification
      n = Rpush::Gcm::Notification.new
      n.app = Rpush::Gcm::App.find_by_name("android_app")
      n.registration_ids = user.device_tokens.pluck(:token)
      n.data = { message: message, title: title, body: body }
      n.priority = 'high'        # Optional, can be either 'normal' or 'high'
      n.content_available = true # Optional
      n.save!

      # Ios push notification
      n = Rpush::Gcm::Notification.new
      n.app = Rpush::Gcm::App.find_by_name("ios_app")
      if n.app.present?
        n.registration_ids = user.device_tokens.pluck(:token)
        n.priority = 'high'        # Optional, can be either 'normal' or 'high'
        n.content_available = true # Optional
        n.notification = { message: message, title: title, body: body, sound: "default" }
        # Optional notification payload. See the reference below for more keys you can use!
        n.save!
      end
    end`

but it is not able to save the notification and throw me the above error

**Comment by kshtzkr** [comment]
Now this is getting stored in my Rpush object as it's error 

` id: 206,
  badge: nil,
  device_token: nil,
  sound: nil,
  alert: nil,
  data: nil,
  expiry: 86400,
  delivered: false,
  delivered_at: nil,
  failed: true,
  failed_at: Mon, 07 Oct 2019 07:05:11 UTC +00:00,
  error_code: nil,
  error_description: "undefined local variable or method `dry_run' for #<Rpush::Client::ActiveRecord::Gcm::Notification:0x0000000007955e28>",
  deliver_after: nil,
  created_at: Mon, 07 Oct 2019 07:05:03 UTC +00:00,
  updated_at: Mon, 07 Oct 2019 07:05:06 UTC +00:00,
  alert_is_json: false,
  type: "Rpush::Client::ActiveRecord::Gcm::Notification",
  collapse_key: nil,
  delay_while_idle: false,
  registration_ids:
   ["cd-1GI7BdmY:APA91bFS9WylebarB74_4gba49NLNZpVAZNBXsi14IGeZFY1SLWOzOFpuKg-qanBGqGz1f-WFAIUrxBcf1m8x3zPGPbN0aaGSuv4F013GYsjxTZ7rLFxUZlTvRsk0uaGbn35Z2ai6FgS",
    "ckF4VEEJQ3Q:APA91bF6wGe5JaNI1aedeLLNbANXvisV_2ENOz038y2PhAgPOloHo8J1cx0yH8CM0YtGdYcmDtn0MAZA1BMYBDPQNPobkjOLx9fnjS5Q_HnqHSNnLN7YNjjFNOxsDO4WuYP20Yf5_IHT",
    "clSxrQKAV8Q:APA91bFJ1gXlZoAWLu53qCqOifNPTFDJTbnvo6f0HDv6m22oQabnwEeZL9nPLATGmEweBPJvsQDlxnykVWAbmNjcYT-Z18oGOlmyhkKXFAe44pAx_lx7kdMiyVxWU7VdVmjUvFTHBaqO",
    "c15CnVaWf0U:APA91bE005vsDTkymUYrdfcLR_c2_xf4-K1ljEbtHfQFoJY3t9dnxKyC_OcadFJfNdMENpyIIcVqHZm2IZCDrjA7BKyd7TucWyuMX7w_IjQhjb7UNgqvc91WWjWlJiuNMFddWmcDuM8H",
    "enNFK82j7sc:APA91bH0vAzcKpjkH58D1QjL-cETENHi9SCOLIhqgPHe1L9m-uG9lVSz9xwpkqbjnyKmmZqFi_18osxzpti_USRsLWNHcpJQ0aS1BbtDrEa5Amp3FlU865CzmQN_05LaDfOFG_E8biGZ",
    "eMTsYInq1aA:APA91bF0JmgR_8LiqobJaRcx3YPjN12BoJKg6p21cf7krNN1hWhIa8o4vwc8Lvr6CcgxHnbGqMVlAt3p9tKfBugCWNLXpOq_QZzIJBDbFamBxEzWU8ZUp6GLlEiyNptAdBq9qd7qiBRS",
    "eETVOhjeojI:APA91bFLSXhy67E2EXz_I3FivS5QIJPCdHjTDUkWkgIHWFQJMk8tJlnt1udkir8jovK1Lsy1zdHoZZQ5-TN55UqWluKYYUjskiN_ek47ow-iIPXCfOlJ73c7_sCsAA4x1OZnHypHirG8",
    "dDpYM84y4Y4:APA91bG7dJArsaV_kaPStqBww7exQc17PrUeIvZ40-m7Ufx_mywMvldtO041JrkEw_hi-GNkhmC6X_AEzt9ubayVhImArWpRB5_-gIzlvLI-1-kgLLuqHIIsq0sl_OdolegAkzoJ97F7",
    "fYekcgI7S1o:APA91bGGHyVfpzHEObuFQT3AITkQM-Z24GHUkqHKLJJ6wGxmu9_9u71d4y6fVJhQOW_y3-mNkcJj0JvZjVX8vml3CMO73Zz2AHQr-x_N0F8wYDEYAK6glBhfFinmlrad_2MR7P-lYpGE"],
  app_id: 5,
  retries: 0,
  uri: nil,
  fail_after: nil,
  processing: false,
  priority: 10,
  url_args: nil,
  category: nil,
  content_available: true,
  notification:
   "{\"message\":\"Accepted Notification\",\"title\":\"void boy has accepted your prospect quote Wor fg\",\"body\":\"void boy has accepted your prospect quote Wor fg\",\"sound\":\"default\"}",
  mutable_content: false,
  external_device_id: nil,
  thread_id: nil>]
`

**Comment by kshtzkr** [comment]
> Please provide the information requested in the issue template. This is too little to investigate.
> 
> We use this feature in production already, so it should work.
> 
> Please make sure you're on the latest version of rpush and ran all DB migrations.

Hey can you please take a look into this why is this happening, Now all my push notification has been stopped and I am not able to use this feature. In any of my platforms

**Comment by aried3r** [comment]
Please provide the information requested in the issue template. Which version of Rpush are you using? Have you run all the migrations? Please also supply all the other relevant information.

This is too little to go by. Thank you!

**Comment by kshtzkr** [comment]
I am using rpush 4.0.0 on the production servers and on staging and QA channel I am using the 4.1.0. \
yes, I have run all the migrations but still, it's not working.

**Comment by aried3r** [comment]
Could you post the output of `Rpush::Notification` in `rails console`?

```console
$ rails console
[1] » Rpush::Notification
=> class Rpush::Client::ActiveRecord::Notification < ActiveRecord::Base {
                  :id => :integer,
               :badge => :integer,
        :device_token => :string,
               :sound => :string,
               :alert => :text,
                :data => :text,
              :expiry => :integer,
           :delivered => :boolean,
        :delivered_at => :datetime,
              :failed => :boolean,
           :failed_at => :datetime,
          :error_code => :integer,
   :error_description => :text,
       :deliver_after => :datetime,
          :created_at => :datetime,
          :updated_at => :datetime,
       :alert_is_json => :boolean,
                :type => :string,
        :collapse_key => :string,
    :delay_while_idle => :boolean,
    :registration_ids => :text,
              :app_id => :integer,
             :retries => :integer,
                 :uri => :string,
          :fail_after => :datetime,
          :processing => :boolean,
            :priority => :integer,
            :url_args => :text,
            :category => :string,
   :content_available => :boolean,
        :notification => :text,
     :mutable_content => :boolean,
  :external_device_id => :string,
           :thread_id => :string,
             :dry_run => :boolean
}
```

As you can see, it outputs `dry_run` at the end (order might be different for you).

Maybe also show your `schema.rb`, it should also contain `dry_run`. Your error reads as though this attribute is missing from your table.

```rb
create_table "rpush_notifications", force: :cascade do |t|
  t.integer "badge"
  t.string "device_token"
  t.string "sound"
  t.text "alert"
  t.text "data"
  t.integer "expiry", default: 86400
  t.boolean "delivered", default: false, null: false
  t.datetime "delivered_at"
  t.boolean "failed", default: false, null: false
  t.datetime "failed_at"
  t.integer "error_code"
  t.text "error_description"
  t.datetime "deliver_after"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.boolean "alert_is_json", default: false, null: false
  t.string "type", null: false
  t.string "collapse_key"
  t.boolean "delay_while_idle", default: false, null: false
  t.text "registration_ids"
  t.integer "app_id", null: false
  t.integer "retries", default: 0
  t.string "uri"
  t.datetime "fail_after"
  t.boolean "processing", default: false, null: false
  t.integer "priority"
  t.text "url_args"
  t.string "category"
  t.boolean "content_available", default: false, null: false
  t.text "notification"
  t.boolean "mutable_content", default: false, null: false
  t.string "external_device_id"
  t.string "thread_id"
  t.boolean "dry_run", default: false, null: false
  t.index ["delivered", "failed", "processing", "deliver_after", "created_at"], name: "index_rpush_notifications_multi", where: "((NOT delivered) AND (NOT failed))"
end
```

**Comment by kshtzkr** [comment]
Now I found the issue migration is not proper on my systems.
Thanks

**Comment by aried3r** [comment]
Glad you found a solution! :)
