### ISSUE TITLE
Wrong number of arguments (given 4, expected 3) when running migrations

### ISSUE THREAD

**Issue by deztrucktor** [rpush/rpush#585]
**Describe the bug**
When running the ActiveRecord migrations in a new rails app, the migrations fail with error `wrong number of arguments (given 4, expected 3)`.

**To Reproduce**
1. Create a new rails app (`rails new rpush-example`)
2. Add rpush to the gemfile (`gem 'rpush'`)
3. Run `bundle install`
4. Run `bundle exec rpush init`
5. Choose to install the ActiveRecord migrations (`y`)
6. Run `bundle exec rake db:migrate`
7. See error `wrong number of arguments (given 4, expected 3)`

**Expected behavior**
The migrations succeed without errors

**Logs and other output**
````
== 20210201124947 AddRpush: migrating =========================================
-- create_table(:rapns_notifications)
   -> 0.0014s
-- add_index(:rapns_notifications, [:delivered, :failed, :deliver_after], {:name=>"index_rapns_notifications_multi"})
   -> 0.0006s
-- create_table(:rapns_feedback)
   -> 0.0005s
-- add_index(:rapns_feedback, :device_token)
   -> 0.0007s
-- add_column(:rapns_notifications, :alert_is_json, :boolean, {:null=>true, :default=>false})
   -> 0.0007s
-- add_column(:rapns_notifications, :app, :string, {:null=>true})
   -> 0.0009s
-- add_column(:rapns_feedback, :app, :string, {:null=>true})
   -> 0.0005s
-- create_table(:rapns_apps)
   -> 0.0006s
-- add_column(:rapns_notifications, :type, :string, {:null=>true})
   -> 0.0005s
-- add_column(:rapns_apps, :type, :string, {:null=>true})
   -> 0.0005s
-- change_column(:rapns_notifications, :type, :string, {:null=>false})
   -> 0.0108s
-- change_column(:rapns_apps, :type, :string, {:null=>false})
   -> 0.0067s
-- change_column(:rapns_notifications, :device_token, :string, {:null=>true, :limit=>64})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 4, expected 3)
/home/andreas/apps/rpush-example/db/migrate/20210201124947_add_rpush.rb:167:in `up'
/home/andreas/apps/rpush-example/db/migrate/20210201124947_add_rpush.rb:31:in `map'
/home/andreas/apps/rpush-example/db/migrate/20210201124947_add_rpush.rb:31:in `up'
/home/andreas/.asdf/installs/ruby/3.0.0/bin/bundle:23:in `load'
/home/andreas/.asdf/installs/ruby/3.0.0/bin/bundle:23:in `<main>'

Caused by:
ArgumentError: wrong number of arguments (given 4, expected 3)
/home/andreas/apps/rpush-example/db/migrate/20210201124947_add_rpush.rb:167:in `up'
/home/andreas/apps/rpush-example/db/migrate/20210201124947_add_rpush.rb:31:in `map'
/home/andreas/apps/rpush-example/db/migrate/20210201124947_add_rpush.rb:31:in `up'
/home/andreas/.asdf/installs/ruby/3.0.0/bin/bundle:23:in `load'
/home/andreas/.asdf/installs/ruby/3.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
````

**System configuration (please complete the following information):**
 - OS: Ubuntu
 - OS version: 20.04.1 LTS
 - Ruby version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
 - Rails version: 6.1.1
 - Rpush version: 5.3.0

**Additional context**
This line runs fine:
```ruby
change_column :rapns_apps, :type, :string, null: false
```
But this one fails:
```ruby
change_column :rapns_notifications, :device_token, :string, { null: true, limit: 64 }
```
Changing it like this works:
```ruby
change_column :rapns_notifications, :device_token, :string, null: true, limit: 64
```

Could it be because of the separation of positional and keyword arguments in Ruby 3.0?

**Comment by benlangfeld** [comment]
We should start by testing on [Ruby 3.0](https://github.com/rpush/rpush/blob/master/.travis.yml#L9-L14) and [Rails 6.1](https://github.com/rpush/rpush/blob/master/.travis.yml#L25-L29). Might you be willing to contribute that @deztrucktor ?

**Comment by andreaslillebo** [comment]
Sure, I'll have a go at that (sorry, posted the issue from the wrong Github account).
