### ISSUE TITLE
 Errno::ECONNRESET, Connection reset by peer after a few minutes when using apns2

### ISSUE THREAD

**Issue by favrik** [rpush/rpush#607]
Hello!,

have you seen anything like this before?  I've searched through the issues, and the ones that are similar are marked as "Stale".

**Describe the bug**
We recently switched to rpush 5.0.0 in order to use **apns2** due to the binary protocol coming to end of life.  I'm not sure if this is a bug, but we are getting the following error between successful IOS push notifications:
```
2021-03-30 03:37:17] [ERROR] Errno::ECONNRESET, Connection reset by peer
/usr/lib/ruby/2.5.0/openssl/buffering.rb:182:in `sysread_nonblock'
/usr/lib/ruby/2.5.0/openssl/buffering.rb:182:in `read_nonblock'
/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.4/lib/net-http2/client.rb:145:in `block in socket_loop'
/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.4/lib/net-http2/client.rb:142:in `loop'
/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.4/lib/net-http2/client.rb:142:in `socket_loop'
/vendor/bundle/ruby/2.5.0/gems/net-http2-0.18.4/lib/net-http2/client.rb:114:in `block (2 levels) in ensure_open'
 ```
 

**To Reproduce**
(note: we start rpush with `bundle exec rpush start -f -e <env>`)
1. Send a push notification to a IOS device: the notification is delivered.
2. Wait around 20 minutes
3. Attempt to send another IOS push notification: we get the error above, and the notification is not delivered

This is the code we are using to send a push notification:
```ruby
def send_ios_notification
    pn = Rpush::Apns2::Notification.new
    pn.app = apns_app
    pn.event_id = event_id
    pn.device_id = id
    pn.device_token = push_id
    pn.badge = sendings.where("status='sent'").count if type == :alert_message

    pn.alert = { title: title, body: message }
    pn.data = ios_data_payload(title, message, type, action)
              .merge(headers: { 'apns-topic' => apns_app.bundle_id })
    pn.save
end

def ios_data_payload(title, message, type, action)
    json = { type: type }
    json[:callback_id] = action[:callback_id] if action
    json[:title] = title if title.present?
    json[:body] = message if message.present?
    { json: json }
end
```

**Expected behavior**
We don't get a connection reset, or the notification is retried successfully

**Logs and other output**

**System configuration (please complete the following information):**
 - OS: [Linux]
 - OS version: [Ubuntu 20.04.2 LTS]
 - Ruby version: [2.5.8p224]
 - Rails version: [5.2.3]
 - Rpush version: [5.0.0]

**Additional context**

**Comment by aried3r** [comment]
Hey @favrik! Sadly I am not a user of the APNs part of the code base, so I'm afraid I cannot directly help out. But since version 5.0.0 that you are using there have been quite some APNs fixes, see the [CHANGELOG.md](https://github.com/rpush/rpush/blob/master/CHANGELOG.md) for more details as well as the [commits since the last release](https://github.com/rpush/rpush/compare/v5.4.0...master).

It would help to figure out if this behavior still exists in the latest version.

**Comment by favrik** [comment]
Thank you @aried3r !

Just remembered we tested up to 5.2.0, but will test with latest version, and see if I'm able to reproduce.

**Comment by CR4567** [comment]
this is a duplicate of #538 
Right now, there is no fix for this problem.

**Comment by benlangfeld** [comment]
@favrik Are you able to confirm that your experience is compatible with the theories in #538 regarding multiple pushes to the same device?

**Comment by favrik** [comment]
Hi @CR4567 and @benlangfeld !

the experience has been similar, in the sense that a notification can fail for a device that was successful previously, or is successful afterwards.

However, I'm not sure how the longer stack trace at #538 was produced (I might ask on the issue later).

We could close as duplicate, the main difference I'm seeing is that I'm able to reproduce every time, seems the current magic number is 13 minutes, so I would send a notification to a device, wait 13 minutes, and then submit again and get an `Connection Reset` error.

I've been testing apnotic, where I get the error as a `Connection timed out`:  once the request is made,  it takes 16.5 minutes to time out,  a workaround is to set a timeout for `client.join`, and reload the connection when `AsyncRequestTimeout` is raised by it.

When reading rpush code, where either the `Connection timed out` or `Connection reset by peer` is thrown, it could be rescued and the connection/client be reset, but for the notification retry mechanism to work, the code would need to be changed I think significantly. :thinking: 

Once I get more details, I'll update this issue, and/or the other one.  Thanks!!

**Comment by edmondchui** [comment]
I experience this issue but it mostly appeared when during the off-peak hours when my Rpush server is idle. During peak time, I'm sending tens of thousands of notifications to Apnd2 over 256 connections. When I increase the number of connections to Apns2 to 512 I saw that happened more. Based on these observations, I suspect Apple is closing the socket on the Apn2 without explicitly telling the developers what is the limit in the Apple Developer documentation.

@favrik and others, what is the number connection specified in your config/initializers/rpush.rb file?

**Comment by OskarAtJoint** [comment]
This is still a problem, any clue/suggestions on how to resolve it ?!

**Comment by taras-viiatyk-yalantis** [comment]
+1

**Comment by kjvarga** [comment]
I had to monkey-patch the code in order to get retries and error handling working correctly.  Otherwise notifications that received the `Errno::ECONNRESET` were stuck in processing forever.  I can't see how it ever worked as-is because the NetHTTP2 lib was swallowing any exceptions (after calling the error callback), so the `rescue` blocks in the `Delivery#perform` method would not be invoked for any exception(s) coming from the HTTP2 socket communications.  The solution was to store the error on the client and check for it after joining, then re-raise in perform if there was an error so that we can either 1) retry or 2) mark failed, depending on the error.

Here are the changes:

```ruby
# RPush uses faulty logic when determining if a notification should be retried.  It only
# recognizes certain responses from APNs as needing a retry.  Which means that any
# failure to actually deliver the notification will result in the notification being marked as failed.
#
# Clearly, we should retry the notification unless - and until - we receive a response from APNs with
# a permanent failure code, or the notification reaches its maximum number of retries.
#
# It is very common to receive "Errno::ECONNRESET: Connection reset by peer" errors from the
# APNs connection, and this issue has not been resolved in RPush.
# @see https://github.com/rpush/rpush/issues/607
#
# The modifications to the original code are:
# 1. Include Errno::ECONNRESET and OpenSSL::SSL::SSLError errors in the list of errors
#    that result in the notification being retried.
# 2. After calling @client.join, we call @client.check_for_error to look for an error in the NetHttp2 client,
#    and if there is one, reraise it.
module Rpush
  module Daemon
    module Apnsp8
      class Delivery
        def perform
          @batch.each_notification do |notification|
            log_info("Preparing notification #{notification.id}")
            prepare_async_post(notification)
          end

          @client.join(timeout: CLIENT_JOIN_TIMEOUT)
          error = @client.check_for_error
          if error
            log_info("Raising error from the client: #{error.class.name}: #{error.message}")
            raise error
          end
        rescue NetHttp2::AsyncRequestTimeout => e
          mark_batch_retryable(10.seconds.from_now, e)
          @client.close
          raise
        rescue OpenSSL::SSL::SSLError,
               Errno::ECONNRESET,
               Errno::ECONNREFUSED,
               SocketError,
               HTTP2::Error::StreamLimitExceeded => e
          mark_batch_retryable(10.seconds.from_now, e)
          raise
        rescue StandardError => e
          mark_batch_failed(e)
          raise
        ensure
          @batch.all_processed
        end
      end
    end
  end
end

# When an error occurs in the NetHttp2 client, it calls the error callback that this
# class registers and swallows the error.  This means that the Delivery class never
# sees it and cannot handle it.  So the notification remains in the
# processing state indefinitely.
#
# The threads which NetHttp2 create have abort_on_exception set to true, so we cannot
# raise the error there otherwise it will immediately terminate the whole process.
# So we store it on the client and check for it after the join call.  If we see an error
# then we raise it in the perform method so that it can be handled appropriately by
# either retrying the notification or marking it as failed.
module Rpush
  module Daemon
    module Dispatcher
      class Apnsp8Http2
        private

        def create_http2_client(app)
          url = URLS[app.environment.to_sym]
          client = NetHttp2::Client.new(url, connect_timeout: DEFAULT_TIMEOUT)

          client.instance_eval do
            @error_mutex = Mutex.new
            @error = nil

            def record_error(error)
              @error_mutex.synchronize { @error = error }
            end

            def check_for_error
              @error_mutex.synchronize do
                return unless @error

                error = @error.dup
                @error = nil
                error
              end
            end
          end

          client.on(:error) do |error|
            client.record_error(error)
            log_error(error)
            reflect(:error, error)
          end

          client
        end
      end
    end
  end
end
```

**Comment by benlangfeld** [comment]
> I had to monkey-patch the code in order to get retries and error handling working correctly.

Would you please submit a PR for that?

**Comment by kjvarga** [comment]
@benlangfeld sure, I can do.  I haven't added tests though.  I'm assuming you'd want it as a complete PR?  I'm going away on a trip in a week or so and back in early March so if the latter, would need to do it then.

**Comment by benlangfeld** [comment]
> @benlangfeld sure, I can do.  I haven't added tests though.  I'm assuming you'd want it as a complete PR?  I'm going away on a trip in a week or so and back in early March so if the latter, would need to do it then.

Just the change on its own in a draft PR would be cool. Who knows, maybe someone finishes it up before you get back to it.

**Comment by kjvarga** [comment]
@benlangfeld I submitted the draft PR here: https://github.com/rpush/rpush/pull/723

**Comment by josef-krabath** [comment]
@kjvarga @benlangfeld @SixiS 
Thanks a lot for the fix! 🚀
